r"""grv_mkcorpus.py - generate the pinned hpoint corpus for Wave 7b.

Each row is:  px pz s1 s2 s3 s4
where s1..s4 are the surfacemap bytes hpoint reads at
    cpos    (h1, row z,   col x  )
    cpos+1  (h2, row z,   col x+1)
    cpos+201(h3, row z+1, col x+1)
    cpos+200(h4, row z+1, col x  )
and cpos = (pz>>14)*200 + (px>>14).

The corpus is DETERMINISTIC and covers:
  * several tile rows/cols (exercises m200 indexing on both axes);
  * sub-tile positions across the 0..16383 icx/icz range, INCLUDING the
    icx+icz = 16383 / 16384 / 16385 boundary that selects the bilinear
    triangle - the one branch hpoint has, and the one a float tolerance
    cannot touch;
  * the corners of surf-byte space (0, 1, 127, 128, 200, 255) and mixed
    slopes, so the height interpolation is exercised both near sea level
    and at full relief.

row = pz>>14 and col = px>>14 are kept in 0..198 so all four corners stay
inside the 40,000-byte p_surfacemap - the honest, in-game-reachable subset
(iperficie never walks a tile whose corners fall off the grid edge).

Writes noctis-harness/grv-corpus.txt.  Re-run freely; output is byte-stable.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))


def tile(px14, pz14, sub=0, s=None):
    """Build one (px,pz,s1,s2,s3,s4) row for tile (col=px14,row=pz14)
    at sub-tile offset `sub` (applied to both axes)."""
    if s is None:
        s = (0, 0, 0, 0)
    px = (px14 << 14) | (sub & 16383)
    pz = (pz14 << 14) | (sub & 16383)
    return (px, pz, s[0], s[1], s[2], s[3])


def rows():
    out = []
    # 1. the icx+icz boundary at three tiles, flat & sloped.
    #    sub=8191 -> icx+icz = 16382 (upper triangle)
    #    sub=8192 -> icx+icz = 16384 (ELSE branch, == is not <)
    #    sub=8193 -> icx+icz = 16386 (else)
    for sub in (0, 1, 8191, 8192, 8193, 16383):
        out.append(tile(10, 10, sub, (30, 60, 90, 0)))
    # 2. asymmetric icx/icz: drive one axis to the limit, the other to zero,
    #    on both branches.
    for (sx, sz) in [(16383, 0), (0, 16383), (16384, 0), (0, 16384),
                     (100, 16284), (16284, 100)]:
        out.append(((10 << 14) | sx, (10 << 14) | sz, 200, 10, 120, 240))
    # 3. surf-byte corners at the tile centre, both branches.
    for s in [(0, 0, 0, 0), (255, 255, 255, 255), (128, 128, 128, 128),
              (1, 255, 1, 255), (255, 1, 255, 1), (127, 128, 129, 200)]:
        out.append(tile(50, 77, 4096, s))      # icx+icz = 8192 < 16384
        out.append(tile(51, 77, 12288, s))     # icx+icz = 24576 >= 16384
    # 4. m200 indexing across the grid: vary col and row widely.
    for (c, r) in [(0, 0), (1, 1), (99, 99), (198, 198), (197, 0),
                   (0, 197), (198, 1), (123, 45)]:
        out.append(tile(c, r, 5000, (80, 100, 120, 90)))
    # 5. one exact-relief case per row 0..49 (varied seed bytes), centre sub.
    for r in range(0, 50):
        s1 = (r * 7) & 255
        out.append(((13 << 14) | 7000, (r << 14) | 7000,
                    s1, (s1 * 3) & 255, (s1 ^ 0x5A) & 255, (255 - s1) & 255))
    return out


def main():
    path = os.path.join(HERE, "grv-corpus.txt")
    with open(path, "w", newline="\n") as fh:
        fh.write("# grv-corpus.txt - pinned hpoint cases (Wave 7b).\n")
        fh.write("# row format: px pz s1 s2 s3 s4  (six signed decimals)\n")
        fh.write("# s1=h1,cpos  s2=h2,cpos+1  s3=h3,cpos+201  s4=h4,cpos+200\n")
        fh.write("# generated by grv_mkcorpus.py - byte-stable.\n")
        for px, pz, s1, s2, s3, s4 in rows():
            fh.write("%d %d %d %d %d %d\n" % (px, pz, s1, s2, s3, s4))
    print("wrote %s (%d cases)" % (path, len(rows())))


if __name__ == "__main__":
    main()
