#!/usr/bin/env python3
"""
pg_mkcorpus.py -- generates the four Wave 6a corpora.

PROVENANCE.  Every vertex, every bbox, every (u,v) pair below is written here
by hand or computed from hand-written values by plain arithmetic.  NOTHING in
this file is read back from pg_ref.exe, from work/pg-out.bin, or from any
other output of the code under test.  That is Recon C trap 4 and it is the
single most important property of these files.

The bbox rule used by the FILL rows is transcribed independently from
TDPOLYGS.H:741-761 (see bbox_of below); it is NOT obtained by running the
oracle's bbox_gate.  Where a FILL row deliberately disagrees with that rule
(class CLIPPED_BBOX) the bbox is written out literally.

Textures and page pre-states are FORMULAS resolved by both sides from their
names, never checked-in binary blobs (Recon C trap 3).

Run:  python pg_mkcorpus.py
Writes: pg_corpus_raster.txt pg_corpus_edge.txt pg_corpus_span.txt
        pg_corpus_proj.txt
"""

import os, struct, sys

HERE = os.path.dirname(os.path.abspath(__file__))

LBX, UBX, LBY, UBY = 5, 311, 10, 190          # NOCTIS-D.H:129-132, x_centro 158


def bbox_of(pts):
    """TDPOLYGS.H:741-761, transcribed by hand.

    The accumulators are SEEDED at the clip rectangle, so they can never
    report an extent outside it in the shrinking direction, and the four
    range tests are asymmetric: >= on the upper bounds, < on the lower.
    """
    ax, bx = LBX, LBY          # max_x, max_y   seeded at the LOWER bounds
    cx, dx = UBX, UBY          # min_x, min_y   seeded at the UPPER bounds
    for (x, y) in pts:
        if not (x >= cx): cx = x
        if not (x <= ax): ax = x
        if not (y >= dx): dx = y
        if not (y <= bx): bx = y
    mx, my, nx, ny = ax, bx, cx, dx
    if not (ax < UBX): mx = UBX
    if not (bx < UBY): my = UBY
    if not (cx >= LBX): nx = LBX
    if not (dx >= LBY): ny = LBY
    return nx, mx, ny, my      # min_x, max_x, min_y, max_y


def mpstr(pts):
    return ";".join("%d,%d" % (x, y) for (x, y) in pts)


def hx(f):
    return "0x%08x" % struct.unpack("<I", struct.pack("<f", f))[0]


def v3(pts):
    return ";".join("%s,%s,%s" % (hx(a), hx(b), hx(c)) for (a, b, c) in pts)


# =============================================================== raster ======

def raster():
    L = []
    A = L.append
    A("# pg_corpus_raster.txt -- surfaces S1 (Segmento), S2 (bbox gate),")
    A("#                        S3 (poly3d drawb: degenerate row, edge stroking, fill)")
    A("#")
    A("# FROZEN FIXTURE.  Generated by pg_mkcorpus.py; do not edit either copy")
    A("# by hand -- regenerate.  Neither implementer may change it; a change is")
    A("# a coordinator commit.")
    A("#")
    A("# ORDER IS PART OF THE FIXTURE.  Both sides consume the rows in file")
    A("# order.  Rows with pre=PRE3 (carry) take the PREVIOUS row's OUTPUT page")
    A("# as their input page, so reordering changes the expected result.")
    A("#")
    A("# PAGE MODEL.  The page is 65540 units indexed j = 0..65539 from the")
    A("# segment origin.  adapted[i] is unit j = 4+i, because farmalloc returns")
    A("# offset 4 (BUFFERMAP 4.1) and `adapted` is `unsigned char far *`")
    A("# (NOCTIS-0.CPP:54).  Units j=0..3 lie BELOW adapted[0]; nothing in")
    A("# Wave 6a may write them.")
    A("#")
    A("# PRE-STATES (formulas over j, not blobs):")
    A("#   PRE0  page[j] = 0")
    A("#   PRE1  page[j] = (j*101) & 255")
    A("#   PRE2  page[j] = 0 except adapted[k]=255 for k in")
    A("#         {32040,32041,32042,32043,32044,32060,32360,48005,48311,60999}")
    A("#   PRE3  carry: the previous case's output page")
    A("#")
    A("# GRAMMAR")
    A("#   SEG  <id> xp= yp= xa= ya= pre=")
    A("#   BBOX <id> n= mp=x0,y0;x1,y1;...")
    A("#   FILL <id> n= mp=... bbox=minx,maxx,miny,maxy colore= flares= entity= pre=")
    A("#")
    A("# The FILL bbox is a SEPARATE pinned input, not derived from that row's")
    A("# mp[].  The original computes the bbox from the PRE-clip vertices and")
    A("# never recomputes it, so for any clipped polygon the two are")
    A("# inconsistent by construction -- see class CLIPPED_BBOX.")
    A("")

    # ---- S1 ---------------------------------------------------------------
    A("# --- S1 Segmento ---")
    segs = [
        ("SEG_VERT_DOWN",   100, 20, 100, 40, "PRE0"),
        ("SEG_VERT_UP",     100, 40, 100, 20, "PRE0"),
        ("SEG_VERT_1PX",    100, 30, 100, 30, "PRE0"),
        ("SEG_VERT_X0",       0, 10,   0, 15, "PRE0"),
        ("SEG_VERT_XMAX",   311, 10, 311, 15, "PRE0"),
        ("SEG_NEARBOT",     150,185, 150,190, "PRE0"),
        ("SEG_HORIZ_R",      20, 50,  60, 50, "PRE0"),
        ("SEG_HORIZ_L",      60, 50,  20, 50, "PRE0"),
        ("SEG_DIAG45",       10, 10,  50, 50, "PRE0"),
        ("SEG_DIAG45_REV",   50, 50,  10, 10, "PRE0"),
        ("SEG_STEEP",       100, 20, 105, 90, "PRE0"),
        ("SEG_STEEP_REV",   105, 90, 100, 20, "PRE0"),
        ("SEG_SHALLOW",      20,100, 200,110, "PRE0"),
        ("SEG_SHALLOW_REV", 200,110,  20,100, "PRE0"),
        ("SEG_ENDPT_A",      50, 60,  60, 60, "PRE0"),
        ("SEG_ENDPT_B",      60, 60,  50, 60, "PRE0"),
        ("SEG_ENDPT_DIAG",   50, 60,  60, 70, "PRE0"),
        ("SEG_LONG",          5, 10, 311,190, "PRE0"),
        ("SEG_LONG_REV",    311,190,   5, 10, "PRE0"),
        ("SEG_ONPRE1",       20, 30, 120, 35, "PRE1"),
        ("SEG_CARRY",        20, 36, 120, 41, "PRE3"),
        ("SEG_TOPLEFT",       5, 10,   6, 11, "PRE0"),
    ]
    for (i, xp, yp, xa, ya, pre) in segs:
        A("SEG %s xp=%d yp=%d xa=%d ya=%d pre=%s" % (i, xp, yp, xa, ya, pre))
    A("")

    # ---- S2 ---------------------------------------------------------------
    A("# --- S2 bbox gate ---")
    bb = [
        ("BBOX_IN",        [(50,50),(100,60),(70,120)]),
        ("BBOX_EQ_UBX",    [(50,50),(311,60),(70,120)]),     # >= side fires
        ("BBOX_EQ_UBY",    [(50,50),(100,190),(70,120)]),    # >= side fires
        ("BBOX_EQ_LBX",    [(5,50),(100,60),(70,120)]),      # <  side does NOT
        ("BBOX_EQ_LBY",    [(50,10),(100,60),(70,120)]),     # <  side does NOT
        ("BBOX_LBX_M1",    [(4,50),(100,60),(70,120)]),      # <  side fires
        ("BBOX_LBY_M1",    [(50,9),(100,60),(70,120)]),
        ("BBOX_UBX_P1",    [(50,50),(312,60),(70,120)]),
        ("BBOX_UBY_P1",    [(50,50),(100,191),(70,120)]),
        ("BBOX_SEED_X",    [(200,50),(250,60),(220,120)]),   # min never below rect
        ("BBOX_SEED_Y",    [(50,150),(100,160),(70,180)]),
        ("BBOX_ALLOUT",    [(-500,-500),(900,900),(400,-20)]),
        ("BBOX_QUAD",      [(20,20),(300,25),(305,180),(15,175)]),
        ("BBOX_HUGE",      [(50,50),(10000000,60),(70,120)]),
    ]
    for (i, pts) in bb:
        A("BBOX %s n=%d mp=%s" % (i, len(pts), mpstr(pts)))
    A("")

    # ---- S3 ---------------------------------------------------------------
    A("# --- S3 poly3d drawb ---")

    def fill(idn, pts, colore=1, fl=0, ent=1, pre="PRE0", bbox=None):
        b = bbox if bbox else bbox_of(pts)
        A("FILL %s n=%d mp=%s bbox=%d,%d,%d,%d colore=%d flares=%d entity=%d pre=%s"
          % (idn, len(pts), mpstr(pts), b[0], b[1], b[2], b[3], colore, fl, ent, pre))

    fill("BIG",        [(40,30),(260,50),(150,170)])
    fill("BIG_PRE1",   [(40,30),(260,50),(150,170)], colore=17, pre="PRE1")
    fill("QUAD",       [(40,30),(260,40),(250,170),(50,160)], colore=9)
    fill("SLIVER1",    [(100,20),(101,20),(101,140),(100,140)], colore=3)
    fill("SLIVERDIAG", [(40,20),(43,20),(80,150),(77,150)], colore=4)
    fill("TALLTHIN",   [(200,10),(201,10),(201,190),(200,190)], colore=5)
    fill("HORIZTOP",   [(30,10),(200,10),(120,80)], colore=6)
    fill("HORIZBOT",   [(30,190),(200,190),(120,120)], colore=7)
    fill("ROWWIDE",    [(30,100),(200,100),(120,100)], colore=8)
    fill("DEGEN",      [(77,77),(77,77),(77,77)], colore=11)
    fill("COLLIN",     [(30,30),(90,60),(150,90)], colore=12)
    fill("RIGHTEDGE",  [(250,40),(311,40),(311,150),(250,150)], colore=13)
    fill("LEFTEDGE",   [(5,40),(60,40),(60,150),(5,150)], colore=14)
    fill("CONCAVE",    [(40,30),(260,30),(150,90),(260,170),(40,170)], colore=15)
    fill("BOWTIE",     [(40,30),(260,170),(40,170),(260,30)], colore=16)
    fill("PRE255MID",  [(40,30),(260,50),(150,170)], colore=18, pre="PRE2")
    fill("PRE255RIGHT",[(30,140),(120,140),(120,160),(30,160)], colore=19, pre="PRE2")
    fill("ADJ255",     [(20,45),(90,45),(90,55),(20,55)], colore=20, pre="PRE2")
    fill("PRE1ALL",    [(60,60),(200,70),(160,150)], colore=21, pre="PRE1")

    A("# SHARED: two triangles sharing an edge, drawn in sequence.  This is the")
    A("# class the game runs every frame and the one most likely to be absent")
    A("# from a hand-written corpus.  The second takes the first's output page.")
    fill("SHARED_A",   [(60,40),(200,40),(60,150)], colore=22)
    fill("SHARED_B",   [(200,40),(200,150),(60,150)], colore=23, pre="PRE3")
    fill("SHARED_C",   [(60,40),(200,40),(200,150),(60,150)], colore=24, pre="PRE3")

    A("# CLIPPED_BBOX: mp[] is post-clip, bbox is from the PRE-clip vertices, so")
    A("# the two disagree.  The original never recomputes the bbox.")
    fill("CLIPPED_BBOX", [(5,40),(311,40),(311,150),(5,150)],
         colore=25, bbox=(5, 311, 10, 190))
    fill("CLIPPED_BBOX2", [(60,60),(200,60),(200,120),(60,120)],
         colore=26, bbox=(5, 311, 10, 190))

    A("# flares dispatch: 1, 2, 4, and the bare-255 fall-through")
    fill("FL1",        [(40,30),(260,50),(150,170)], colore=0x2A, fl=1, pre="PRE1")
    fill("FL1_CLAMP",  [(40,30),(260,50),(150,170)], colore=0x3F, fl=1, pre="PRE1")
    fill("FL2",        [(40,30),(260,50),(150,170)], colore=0x2A, fl=2, pre="PRE1")
    fill("FL2_PRE0",   [(40,30),(260,50),(150,170)], colore=0x2A, fl=2, pre="PRE0")
    fill("FL4",        [(40,30),(260,50),(150,170)], colore=0x41, fl=4, ent=1)
    fill("FL4_WRAP",   [(40,30),(260,50),(150,170)], colore=0x41, fl=4, ent=0x81)
    fill("FL4_ENT7",   [(40,30),(260,50),(150,170)], colore=0x00, fl=4, ent=7)
    fill("FL_NOCASE3", [(40,30),(260,50),(150,170)], colore=27, fl=3)
    fill("FL_NOCASE5", [(40,30),(260,50),(150,170)], colore=28, fl=5)
    fill("FL_NOCASE6", [(40,30),(260,50),(150,170)], colore=29, fl=6)
    fill("FL1_ROW",    [(30,100),(200,100),(120,100)], colore=0x20, fl=1, pre="PRE1")

    A("# COL255: the fill paints with the sentinel colour, so the NEXT polygon's")
    A("# scan sees this one's interior as a boundary.  Instrumented, not audited.")
    fill("COL255_A",   [(40,30),(260,50),(150,170)], colore=255)
    fill("COL255_B",   [(60,60),(240,70),(150,150)], colore=30, pre="PRE3")
    return "\n".join(L) + "\n"


# ================================================================= edge ======

def edge():
    L = []
    A = L.append
    A("# pg_corpus_edge.txt -- surface S4 (polymap ipart/fpart edge walk)")
    A("#")
    A("# FROZEN FIXTURE.  Generated by pg_mkcorpus.py.")
    A("#")
    A("# GRAMMAR:  EDGE <id> n= mp=x0,y0;... miny= maxy=")
    A("#")
    A("# ipart[] is the LEFT boundary (seeded ubxl=311); fpart[] is the RIGHT")
    A("# boundary (seeded lbxl=5).  TDPOLYGS.H:2539.  The names are inverted")
    A("# relative to the obvious reading.")
    A("#")
    A("# miny/maxy are PINNED inputs, not recomputed from mp[].  In polymap they")
    A("# come from the projector's y-only extent after the two normalisation")
    A("# steps at :2487-2499, which is a different quantity from min(mp.y).")
    A("")

    def E(idn, pts, y0, y1):
        A("EDGE %s n=%d mp=%s miny=%d maxy=%d" % (idn, len(pts), mpstr(pts), y0, y1))

    E("ED_TRI",        [(50,30),(200,60),(120,150)], 30, 150)
    E("ED_QUAD",       [(50,30),(200,40),(210,150),(40,140)], 30, 150)
    E("ED_ABOVE_TOP",  [(50,-40),(200,-30),(120,150)], 10, 150)
    E("ED_CROSS_TOP",  [(50,-5),(200,20),(120,150)], 10, 150)
    E("ED_CROSS_BOT",  [(50,30),(200,60),(120,260)], 30, 190)
    E("ED_BOTH",       [(50,-100),(200,-90),(120,400)], 10, 190)
    E("ED_ONESCAN",    [(50,100),(200,101),(120,101)], 100, 101)
    E("ED_HORIZ",      [(50,100),(200,100),(120,150)], 100, 150)
    E("ED_TALL",       [(60,10),(70,190),(200,100)], 10, 190)
    E("ED_CLAMP_LEFT", [(-40000,50),(200,60),(120,150)], 50, 150)
    E("ED_CLAMP_RIGHT",[(40000,50),(200,60),(120,150)], 50, 150)
    A("# bndx landing exactly on k+0.5 at every scanline: dx/dy = 1/2 with an")
    A("# odd start, so the accumulator alternates .0 and .5.  This is the")
    A("# nearest-even site a truncating port gets wrong.")
    E("ED_TIE_HALF",   [(51,20),(101,120),(60,120)], 20, 120)
    E("ED_TIE_HALF2",  [(50,20),(100,120),(61,120)], 20, 120)
    A("# quarter steps: .25/.5/.75 sequence, only one of four rows is a tie")
    E("ED_TIE_QTR",    [(50,20),(75,120),(60,120)], 20, 120)
    A("# negative slope, so a truncating port biases the other way")
    E("ED_NEG_SLOPE",  [(200,20),(150,120),(210,120)], 20, 120)
    A("# long edge: 170 scanlines of accumulator drift")
    E("ED_DRIFT",      [(20,10),(300,180),(25,180)], 10, 180)
    E("ED_DRIFT_REV",  [(300,10),(20,180),(295,180)], 10, 180)
    A("# mp[] above 2**24, as a blown-up near-plane interpolation produces")
    E("ED_HUGE",       [(20000000,50),(200,60),(120,150)], 50, 150)
    A("# ity == jty exactly, reachable only through the top clip: an edge from")
    A("# y=5 to y=10 has ity=lbyl=10 and jty=10, and `jnl noifor` (ity>=jty)")
    A("# makes it contribute NOTHING.  The source comment says h<=jty; the code")
    A("# says otherwise.")
    E("ED_ITY_EQ_JTY", [(60,5),(120,10),(200,60)], 10, 60)
    A("# ED_ITY_EQ_JTY only moves the record if the skipped edge would have")
    A("# contributed a value no OTHER edge already covers.  When the edge ends")
    A("# on a shared vertex at y=lbyl the next edge starts from the same x, so")
    A("# the write is absorbed.  Here BOTH edges incident on the y=10 vertex")
    A("# come from above it, so both are skipped and row 10 keeps its seeds")
    A("# (ipart=311, fpart=5, an empty span).  `<=` would fill it with 160:160")
    A("# and the polygon would stop vanishing.")
    E("ED_ITY_EQ_JTY2", [(20,2),(300,2),(160,10)], 10, 20)
    A("# top clip landing on an exact half: kx = 5/20 = 0.25 exactly, so")
    A("# (lbyl-y1)*kx = 10*0.25 = 2.5 exactly and x1 = 51 is ODD.  Rounding the")
    A("# SUM gives rne(53.5) = 54; rounding the PRODUCT first gives 51+2 = 53.")
    A("# This single row is what separates the two.")
    E("ED_TIE_TOPCLIP", [(51,0),(56,20),(200,100)], 10, 100)
    E("ED_TIE_TOPCLIP2",[(53,0),(58,20),(200,100)], 10, 100)
    A("# closing edge mp[vr22] = mp[0] must be walked too")
    E("ED_CLOSING",    [(200,30),(210,150),(50,60)], 30, 150)
    return "\n".join(L) + "\n"


# ================================================================= span ======

def span():
    L = []
    A = L.append
    A("# pg_corpus_span.txt -- surface S5 (polymap span engine)")
    A("#")
    A("# FROZEN FIXTURE.  Generated by pg_mkcorpus.py.")
    A("#")
    A("# GRAMMAR:")
    A("#   SPAN <id> i= ipart= fpart= tinta= escr= flares= cull= half= maxy=")
    A("#             tex= uv=u0,v0;u1,v1;... pre=")
    A("#")
    A("# uv[] is the ORDERED list of the row's (u,v) values as int32: pair 0 is")
    A("# the value computed at `trace` before the first block, pair k>=1 is the")
    A("# value after block k's `fistp u / fistp v`.  Block k reads pair k-1 into")
    A("# EAX/EDX and derives its per-pixel step as (pair[k]-pair[k-1]) >> 4,")
    A("# a 32-bit arithmetic shift; the accumulators themselves are 16-BIT")
    A("# (`add ax,bp` carries no 0x66 prefix).")
    A("#")
    A("# TEXTURES (formulas over the 64 KiB window reachable through fs:[bx]):")
    A("#   TEX0  t[i] = (i*37 + 11) & 255")
    A("#   TEX1  t[i] = ((i>>8) ^ (i & 255)) & 255")
    A("#   TEX2  t[i] = 1")
    A("#   TEX3  t[i] = 0 except t[0]=t[32768]=t[65535]=255")
    A("#")
    A("# escr defaults to 0xE0.  The two scratch pixels adapted[63996]/[63997]")
    A("# (es:[0xFA00]/[0xFA01]) carry tinta and escrescenze and are present in")
    A("# every case as a canary.")
    A("")

    def uvlist(u0, v0, du, dv, nblk):
        # nblk+1 pairs are consumed; two spares are appended so that a sabotage
        # which lengthens the span (e.g. a right-inclusive `sections`) still
        # has input and fails on the PAGE rather than on a parse error.
        return ";".join("%d,%d" % (u0 + k*du, v0 + k*dv) for k in range(nblk+3))

    def S(idn, i, ip, fp, uv, tinta=0, escr=0xE0, fl=0, cull=0, half=0,
          tex="TEX0", pre="PRE0", maxy=None):
        my = maxy if maxy is not None else i+1
        A("SPAN %s i=%d ipart=%d fpart=%d tinta=%d escr=%d flares=%d cull=%d "
          "half=%d maxy=%d tex=%s uv=%s pre=%s"
          % (idn, i, ip, fp, tinta, escr, fl, cull, half, my, tex, uv, pre))

    # block-boundary classes (non-culling: 16 px per block)
    S("SP_SHORT",   100, 100, 105, uvlist(0, 0, 16*64, 16*32, 1))
    S("SP_EXACT16", 100, 100, 116, uvlist(0, 0, 16*64, 16*32, 1))
    S("SP_EXACT17", 100, 100, 117, uvlist(0, 0, 16*64, 16*32, 2))
    S("SP_EXACT32", 100, 100, 132, uvlist(0, 0, 16*64, 16*32, 2))
    S("SP_EXACT33", 100, 100, 133, uvlist(0, 0, 16*64, 16*32, 3))
    S("SP_LONG",    100,   6, 310, uvlist(0, 0, 16*64, 16*32, 20))
    S("SP_ZERO",    100, 100, 100, uvlist(0, 0, 0, 0, 1))
    S("SP_NEGSEC",  100, 150, 120, uvlist(0, 0, 0, 0, 1))

    # accumulator wrap
    S("SP_UWRAP",   100, 100, 132, uvlist(0x0FFF0, 0, 16*0x100, 0, 2))
    S("SP_VWRAP",   100, 100, 132, uvlist(0, 0x0FFF0, 0, 16*0x100, 2))
    S("SP_FULLWRAP",100, 100, 132, uvlist(0x0FF00, 0x0FF00, 16*0x180, 16*0x180, 2))
    S("SP_NEGSTEP", 100, 100, 132, uvlist(0x8000, 0x8000, -16*0x40, -16*0x20, 2))
    A("# step_u negative and not a multiple of 16: sar 4 truncates toward -inf")
    S("SP_SARTRUNC",100, 100, 132, uvlist(0x8000, 0x8000, -17, -33, 2))

    # texture probes
    S("SP_TEX1",    100, 100, 132, uvlist(0, 0, 16*257, 16*257, 2), tex="TEX1")
    S("SP_TEX2",    100, 100, 132, uvlist(0, 0, 16*64, 16*32, 2),   tex="TEX2")
    S("SP_TEX3",    100, 100, 132, uvlist(0, 0, 16*0x101, 16*0x101, 2), tex="TEX3")

    # combine variants -- each with a NON-ZERO pre-state, since four of the
    # five read the destination
    for name, fl in (("INT",0),("TRANSP",1),("BRIGHT",2),("MERGER",4),("BUMP",8)):
        S("SP_%s" % name,  100, 100, 132, uvlist(0, 0, 16*64, 16*32, 2),
          tinta=0x11, fl=fl, pre="PRE1")
        S("SP_%s_P0" % name, 102, 100, 132, uvlist(0, 0, 16*64, 16*32, 2),
          tinta=0x11, fl=fl, pre="PRE0")
    A("# bright clamps at 0x3E, not 0x3F")
    S("SP_BRIGHT_CLAMP", 100, 100, 132, uvlist(0, 0, 16*64, 16*32, 2),
      tinta=0, fl=2, tex="TEX0", pre="PRE1")
    A("# merger's 8-bit `or` bleeds the shifted value into the top 2 bits")
    S("SP_MERGER_BLEED", 100, 100, 132, uvlist(0, 0, 16*64, 16*32, 2),
      tinta=0xC0, fl=4, pre="PRE1")
    A("# bumper with n=(tinta+texel)&7 == 0 writes one row BELOW; n==1 writes")
    A("# the SAME row.  TEX2 makes every texel 1, so n = (tinta+1)&7.")
    S("SP_BUMP_N0", 100, 100, 116, uvlist(0, 0, 16*64, 16*32, 1),
      tinta=7, fl=8, tex="TEX2", pre="PRE1")
    S("SP_BUMP_N1", 100, 100, 116, uvlist(0, 0, 16*64, 16*32, 1),
      tinta=0, fl=8, tex="TEX2", pre="PRE1")
    S("SP_BUMP_N7", 100, 100, 116, uvlist(0, 0, 16*64, 16*32, 1),
      tinta=6, fl=8, tex="TEX2", pre="PRE1")

    # flares dispatch is a bit test WITH PRIORITY, not a switch.
    A("# groundflares = 2 + 2*cz reaches 2,4,6,8 (NOCTIS-1.CPP:1986) and feeds")
    A("# polymap, whose dispatch is a bit test with priority.  6 and 10")
    A("# exercise the priority order: 6 must take the BRIGHT arm, not MERGER.")
    S("SP_FL6",  100, 100, 132, uvlist(0, 0, 16*64, 16*32, 2), tinta=0x11, fl=6, pre="PRE1")
    S("SP_FL10", 100, 100, 132, uvlist(0, 0, 16*64, 16*32, 2), tinta=0x11, fl=10, pre="PRE1")
    S("SP_FL3",  100, 100, 132, uvlist(0, 0, 16*64, 16*32, 2), tinta=0x11, fl=3, pre="PRE1")

    # culling: 32 px per block, cl = min(sections+2,32) then >>1
    A("# culling: sections 32 gives cl=34 -> 17 iterations -> 34 pixels drawn")
    A("# for a 32-wide span.  Overdraw 2.  Original behaviour, not a bug.")
    S("SP_C_EXACT32", 100, 100, 132, uvlist(0, 0, 32*64, 32*32, 2), cull=1, pre="PRE1")
    S("SP_C_EXACT33", 100, 100, 133, uvlist(0, 0, 32*64, 32*32, 3), cull=1, pre="PRE1")
    S("SP_C_SHORT",   100, 100, 103, uvlist(0, 0, 32*64, 32*32, 1), cull=1, pre="PRE1")
    S("SP_C_LONG",    100,   6, 310, uvlist(0, 0, 32*64, 32*32, 12), cull=1, pre="PRE1")
    A("# antibloom and c_antibloom are INCONSISTENT in the original: the culled")
    A("# variant gives both pixels the LEFT pixel's top 2 bits.  Reproduced.")
    S("SP_C_BRIGHT",  100, 100, 132, uvlist(0, 0, 32*64, 32*32, 2),
      tinta=0x11, fl=2, cull=1, pre="PRE1")
    S("SP_C_MERGER",  100, 100, 132, uvlist(0, 0, 32*64, 32*32, 2),
      tinta=0x11, fl=4, cull=1, pre="PRE1")
    S("SP_C_BUMP",    100, 100, 132, uvlist(0, 0, 32*64, 32*32, 2),
      tinta=7, fl=8, cull=1, tex="TEX2", pre="PRE1")

    # halfscan: reads element i-1 (byte offset si-2), writes rows i and i+1,
    # and reads at [di-316] = one row up, PLUS the offset-4 convention.
    A("# halfscan reads element i-1 and writes rows i and i+1 from [di-316],")
    A("# which is one row up AND the +4 farmalloc offset.")
    S("SP_HALF",      100, 100, 132, uvlist(0, 0, 16*64, 16*32, 2),
      tinta=0x11, half=1, maxy=150, pre="PRE1")
    S("SP_HALF_END",  100, 100, 132, uvlist(0, 0, 16*64, 16*32, 2),
      tinta=0x11, half=1, maxy=100, pre="PRE1")
    S("SP_HALF_CULL", 100, 100, 132, uvlist(0, 0, 32*64, 32*32, 2),
      tinta=0x11, half=1, cull=1, maxy=150, pre="PRE1")

    # clip-edge rows
    S("SP_ATLBX",  100,   5,  40, uvlist(0, 0, 16*64, 16*32, 3), pre="PRE1")
    S("SP_ATUBX",  100, 280, 311, uvlist(0, 0, 16*64, 16*32, 2), pre="PRE1")
    S("SP_TOPROW",  10, 100, 132, uvlist(0, 0, 16*64, 16*32, 2), pre="PRE1")
    S("SP_BOTROW", 190, 100, 132, uvlist(0, 0, 16*64, 16*32, 2), pre="PRE1", maxy=190)
    return "\n".join(L) + "\n"


# ================================================================= proj ======

def proj():
    L = []
    A = L.append
    A("# pg_corpus_proj.txt -- surfaces S6 (projection, BOUNDED) and")
    A("#                       S7 (getcoords, EXACT)")
    A("#")
    A("# FROZEN FIXTURE.  Generated by pg_mkcorpus.py.")
    A("#")
    A("# All coordinates are hex float32 BIT PATTERNS.  A shared decimal parser")
    A("# would be a shared divergence, so there is not one.")
    A("#")
    A("# GRAMMAR")
    A("#   PROJ  <id> which=poly3d|polymap nrv= v=x,y,z;... cam= ang= dpp= uneg=")
    A("#              colore= flares= entity= draw=")
    A("#   ROWUV <id> nrv= v= cam= ang= dpp= i= ipart=")
    A("#   GETC  <id> p=x,y,z cam= ang= dpp=")
    A("#   FACING<id> v=x,y,z;x,y,z;x,y,z cam= ang= dpp=")
    A("#")
    A("# dpp defaults to 210.0f (NOCTIS.CPP:2214 followed by")
    A("# change_camera_lens()), NOT the header's 200.")
    A("#")
    A("# BLOCK `EXACT`: dpp=128, camera at the origin, all angles zero, every")
    A("# vertex at z=128.  Then every intermediate is dyadic and the screen")
    A("# vertex is exactly (x+158, y+100); rzf = 128 >= uneg so doflag == nrv")
    A("# and the near-plane walk is bypassed.  Rounding is not exercised at")
    A("# all: this block isolates topology from arithmetic.")
    A("")

    D128 = hx(128.0)

    def P(idn, pts, which="poly3d", cam=(0,0,0), ang=(0,0,0), dppv=210.0,
          draw=0, colore=1, fl=0, ent=1, unegv=100.0):
        A("PROJ %s which=%s nrv=%d v=%s cam=%s,%s,%s ang=%s,%s,%s dpp=%s uneg=%s "
          "colore=%d flares=%d entity=%d draw=%d"
          % (idn, which, len(pts), v3(pts),
             hx(cam[0]), hx(cam[1]), hx(cam[2]),
             hx(ang[0]), hx(ang[1]), hx(ang[2]),
             hx(dppv), hx(unegv), colore, fl, ent, draw))

    A("# --- EXACT block (dpp = 128, z = 128) ---")
    P("EX_TRI",  [(-100.0,-60.0,128.0),(100.0,-60.0,128.0),(0.0,60.0,128.0)], dppv=128.0)
    P("EX_QUAD", [(-100.0,-60.0,128.0),(100.0,-60.0,128.0),(100.0,60.0,128.0),
                  (-100.0,60.0,128.0)], dppv=128.0)
    P("EX_TRI_DRAW", [(-100.0,-60.0,128.0),(100.0,-60.0,128.0),(0.0,60.0,128.0)],
      dppv=128.0, draw=1, colore=33)
    P("EX_EDGE_UBX", [(153.0,-60.0,128.0),(100.0,-60.0,128.0),(0.0,60.0,128.0)],
      dppv=128.0)   # x -> 158+153 = 311 exactly
    P("EX_EDGE_LBX", [(-153.0,-60.0,128.0),(100.0,-60.0,128.0),(0.0,60.0,128.0)],
      dppv=128.0)   # x -> 5 exactly
    P("EX_EDGE_UBY", [(-100.0,90.0,128.0),(100.0,-60.0,128.0),(0.0,60.0,128.0)],
      dppv=128.0)   # y -> 190 exactly
    P("EX_EDGE_LBY", [(-100.0,-90.0,128.0),(100.0,-60.0,128.0),(0.0,60.0,128.0)],
      dppv=128.0)   # y -> 10 exactly
    P("EX_POLYMAP", [(-100.0,-60.0,128.0),(100.0,-60.0,128.0),(100.0,60.0,128.0),
                     (-100.0,60.0,128.0)], which="polymap", dppv=128.0)
    A("")

    A("# --- near-plane walk: the four emit cases ---")
    P("NEAR_ALL_IN",  [(-50.0,-30.0,300.0),(50.0,-30.0,300.0),(0.0,30.0,300.0)])
    P("NEAR_ALL_OUT", [(-50.0,-30.0,10.0),(50.0,-30.0,10.0),(0.0,30.0,10.0)])
    P("NEAR_1IN",     [(-50.0,-30.0,300.0),(50.0,-30.0,10.0),(0.0,30.0,20.0)])
    P("NEAR_2IN",     [(-50.0,-30.0,300.0),(50.0,-30.0,400.0),(0.0,30.0,20.0)])
    P("NEAR_ADJ",     [(-50.0,-30.0,300.0),(50.0,-30.0,400.0),(0.0,30.0,20.0),
                       (-60.0,40.0,15.0)])
    P("NEAR_OPP",     [(-50.0,-30.0,300.0),(50.0,-30.0,20.0),(60.0,30.0,400.0),
                       (-60.0,40.0,15.0)])
    A("# the exact-equality degenerate guard: Zv == Zo, so no division happens")
    P("NEAR_DEGEN",   [(-50.0,-30.0,300.0),(50.0,-30.0,50.0),(0.0,30.0,50.0)])
    P("NEAR_ATUNEG",  [(-50.0,-30.0,100.0),(50.0,-30.0,300.0),(0.0,30.0,50.0)])
    A("# a near-degenerate but WELL-CONDITIONED denominator: rzf 0.001 apart,")
    A("# which is far above the 2**-10 relative threshold and is exactly the")
    A("# size an epsilon borrowed from stick3d (|diff| > 0.01) would swallow.")
    P("NEAR_EPS", [(-50.0,-30.0,100.0),(50.0,-30.0,99.999),(0.0,30.0,300.0)])
    A("# a vertex EXACTLY at uneg: >= keeps it, > drops it, and with draw=1 the")
    A("# difference reaches the page.")
    P("NEAR_ATUNEG_DRAW", [(-50.0,-30.0,300.0),(50.0,-30.0,100.0),(0.0,30.0,300.0)],
      draw=1, colore=55)
    A("# NEAR_ILL: denominators of a few ULP.  COUNTED AND REPORTED; values and")
    A("# topology are NOT GRADED for these rows.  zk goes to ~1e7 and the")
    A("# emitted vertex lands arbitrarily far off screen, which changes which")
    A("# 2-D clip cases fire -- no envelope is coherent there.")
    z1 = 300.0
    z2 = struct.unpack("<f", struct.pack("<I",
         struct.unpack("<I", struct.pack("<f", z1))[0] + 2))[0]
    P("NEAR_ILL",     [(-50.0,-30.0,z1),(50.0,-30.0,z2),(0.0,30.0,50.0)])
    A("")

    A("# --- 2-D clip stages ---")
    P("CLIP2_TOP",    [(-50.0,-400.0,300.0),(50.0,-30.0,300.0),(0.0,30.0,300.0)])
    P("CLIP3_BOT",    [(-50.0,400.0,300.0),(50.0,30.0,300.0),(0.0,-30.0,300.0)])
    P("CLIP4_LEFT",   [(-900.0,-30.0,300.0),(50.0,-30.0,300.0),(0.0,30.0,300.0)])
    P("CLIP5_RIGHT",  [(900.0,-30.0,300.0),(-50.0,-30.0,300.0),(0.0,30.0,300.0)])
    P("CLIP_ALL4",    [(-900.0,-400.0,300.0),(900.0,-400.0,300.0),
                       (900.0,400.0,300.0),(-900.0,400.0,300.0)])
    P("CLIP_CORNER",  [(-900.0,-400.0,300.0),(50.0,-30.0,300.0),(0.0,30.0,300.0)])
    P("CLIP_MANY",    [(-900.0,-400.0,300.0),(900.0,-400.0,300.0),
                       (900.0,400.0,300.0),(-900.0,400.0,300.0)], draw=1, colore=44)
    A("")

    A("# --- magnitude and sign ---")
    for m in (1e3, 1e4, 1e5, 1e6, 3.8e6):
        P("MAG_%g" % m, [(-0.02*m,-0.012*m,m),(0.02*m,-0.012*m,m),(0.0,0.012*m,m)])
    P("SIGN_TL", [(-150.0,-88.0,300.0),(-140.0,-88.0,300.0),(-145.0,-80.0,300.0)])
    P("SIGN_TR", [( 150.0,-88.0,300.0),( 140.0,-88.0,300.0),( 145.0,-80.0,300.0)])
    P("SIGN_BL", [(-150.0, 88.0,300.0),(-140.0, 88.0,300.0),(-145.0, 80.0,300.0)])
    P("SIGN_BR", [( 150.0, 88.0,300.0),( 140.0, 88.0,300.0),( 145.0, 80.0,300.0)])
    A("")

    A("# --- angles: the rototranslation is not exercised at alfa=beta=0 ---")
    for (a, b) in ((30.0,0.0),(0.0,45.0),(15.0,200.0),(-20.0,355.0)):
        P("ANG_%g_%g" % (a,b),
          [(-50.0,-30.0,300.0),(50.0,-30.0,300.0),(0.0,30.0,300.0)], ang=(a,b,0.0))
    P("CAM_OFF", [(-50.0,-30.0,300.0),(50.0,-30.0,300.0),(0.0,30.0,300.0)],
      cam=(11.5,-7.25,40.0))
    A("# gamma != 0 must raise the OUT-OF-SCOPE flag, not silently roll")
    P("GAMMA_NZ", [(-50.0,-30.0,300.0),(50.0,-30.0,300.0),(0.0,30.0,300.0),
                   (-40.0,30.0,300.0)], which="polymap", ang=(0.0,0.0,17.0))
    A("")

    A("# --- polymap projector (different nucleus: dpp/Zc, unit matrix) ---")
    P("PM_TRI",  [(-50.0,-30.0,300.0),(50.0,-30.0,300.0),(0.0,30.0,300.0)],
      which="polymap")
    P("PM_QUAD", [(-50.0,-30.0,300.0),(50.0,-30.0,300.0),(50.0,30.0,300.0),
                  (-50.0,30.0,300.0)], which="polymap")
    P("PM_NEAR", [(-50.0,-30.0,300.0),(50.0,-30.0,20.0),(50.0,30.0,300.0),
                  (-50.0,30.0,300.0)], which="polymap")
    P("PM_OFFTOP", [(-50.0,-3000.0,300.0),(50.0,-3000.0,300.0),(0.0,-2900.0,300.0)],
      which="polymap")
    P("PM_ANG",  [(-50.0,-30.0,300.0),(50.0,-30.0,300.0),(50.0,30.0,300.0),
                  (-50.0,30.0,300.0)], which="polymap", ang=(12.0,34.0,0.0))
    A("")

    A("# --- fst-asymmetry probes ---")
    A("# At alfa=beta=0 the rototranslation multiplies by exactly 1 and 0, so")
    A("# `fst zz` narrowing is a no-op and the four asymmetry sites are")
    A("# UNOBSERVABLE by construction.  These rows use awkward camera offsets")
    A("# (so z-cam_z, x-cam_x, y-cam_y are NOT exactly representable in")
    A("# binary32) together with non-zero angles (so the products are genuinely")
    A("# rounded).  The constants are hand-chosen decimal fractions with long")
    A("# binary expansions; they were NOT searched for with the code under")
    A("# test, which would make the corpus self-derived.")
    awk = [(1234.5678, -987.3125, 7654.321),
           (-2345.6789, 876.54321, 9876.5432),
           (3456.789, -1234.5678, 8765.4321),
           (-4567.8912, 2345.6789, 7654.3219)]
    P("FST_P3D", awk, ang=(23.0, 41.0, 0.0), cam=(1234.5678, -987.3125, 6543.21))
    P("FST_PMAP", awk, which="polymap", ang=(23.0, 41.0, 0.0),
      cam=(1234.5678, -987.3125, 6543.21))
    awk2 = [(1.0/3.0, 2.0/7.0, 3800000.5),
            (-1.0/9.0, 5.0/11.0, 3800001.5),
            (7.0/13.0, -3.0/17.0, 3800002.5),
            (-11.0/19.0, 13.0/23.0, 3800003.5)]
    P("FST_BIG", awk2, ang=(23.0, 41.0, 0.0), cam=(0.1, 0.3, 0.7))
    P("FST_BIGPM", awk2, which="polymap", ang=(23.0, 41.0, 0.0), cam=(0.1, 0.3, 0.7))
    P("FST_TINY", [(0.1,0.3,100.7),(0.7,-0.3,101.3),(-0.9,0.1,102.9),(0.5,0.9,103.1)],
      which="polymap", ang=(7.0, 13.0, 0.0), cam=(0.01, 0.02, 0.03))
    A("")
    A("# --- u/v derivation from the gradient basis ---")
    def RU(idn, pts, i, ipv, ang=(0,0,0), dppv=210.0, cam=(0.0,0.0,0.0)):
        A("ROWUV %s nrv=%d v=%s cam=%s,%s,%s ang=%s,%s,%s dpp=%s i=%d ipart=%d"
          % (idn, len(pts), v3(pts), hx(cam[0]),hx(cam[1]),hx(cam[2]),
             hx(ang[0]),hx(ang[1]),hx(ang[2]), hx(dppv), i, ipv))
    quad = [(-50.0,-30.0,300.0),(50.0,-30.0,300.0),(50.0,30.0,300.0),(-50.0,30.0,300.0)]
    RU("UV_MID",  quad, 100, 140)
    RU("UV_TOP",  quad,  80, 120)
    RU("UV_LEFT", quad, 100,   5)
    RU("UV_RIGHT",quad, 100, 305)
    RU("UV_ANG",  quad, 100, 140, ang=(12.0,34.0,0.0))
    RU("UV_FST",  awk,  100, 140, ang=(23.0,41.0,0.0), cam=(1234.5678,-987.3125,6543.21))
    RU("UV_FST2", awk2, 100, 140, ang=(23.0,41.0,0.0), cam=(0.1,0.3,0.7))
    RU("UV_FST3", awk2, 140,  40, ang=(23.0,41.0,0.0), cam=(0.1,0.3,0.7))
    RU("UV_FST4", awk,  60,  250, ang=(23.0,41.0,0.0), cam=(1234.5678,-987.3125,6543.21))
    A("")

    A("# --- S7 getcoords: 100% exact, on points rounding to exactly 5/311/10/190")
    A("# The test at :3200 is strict (> and <), so a point landing exactly on a")
    A("# bound returns 0.  These rows are the only FLOATSITES-MAJOR site here.")
    def G(idn, p, cam=(0,0,0), ang=(0,0,0), dppv=210.0):
        A("GETC %s p=%s,%s,%s cam=%s,%s,%s ang=%s,%s,%s dpp=%s"
          % (idn, hx(p[0]),hx(p[1]),hx(p[2]),
             hx(cam[0]),hx(cam[1]),hx(cam[2]),
             hx(ang[0]),hx(ang[1]),hx(ang[2]), hx(dppv)))
    G("GC_CENTRE",  (0.0, 0.0, 300.0))
    G("GC_UBX",     (153.0, 0.0, 128.0), dppv=128.0)   # _x_ == 311 exactly
    G("GC_UBX_M1",  (152.0, 0.0, 128.0), dppv=128.0)   # _x_ == 310
    G("GC_LBX",     (-153.0, 0.0, 128.0), dppv=128.0)  # _x_ == 5 exactly
    G("GC_LBX_P1",  (-152.0, 0.0, 128.0), dppv=128.0)
    G("GC_UBY",     (0.0, 90.0, 128.0), dppv=128.0)    # _y_ == 190 exactly
    G("GC_UBY_M1",  (0.0, 89.0, 128.0), dppv=128.0)
    G("GC_LBY",     (0.0, -90.0, 128.0), dppv=128.0)   # _y_ == 10 exactly
    G("GC_LBY_P1",  (0.0, -89.0, 128.0), dppv=128.0)
    G("GC_BEHIND",  (0.0, 0.0, 50.0))
    G("GC_ATUNEG",  (0.0, 0.0, 100.0))
    G("GC_FAR",     (0.0, 0.0, 3.8e6))
    G("GC_ANG",     (10.0, 20.0, 300.0), ang=(15.0,25.0,0.0))
    G("GC_CAMOFF",  (10.0, 20.0, 300.0), cam=(3.5,-2.25,17.0))
    A("")
    A("# --- facing ---")
    def F(idn, pts, cam=(0,0,0)):
        A("FACING %s v=%s cam=%s,%s,%s ang=%s,%s,%s dpp=%s"
          % (idn, v3(pts), hx(cam[0]),hx(cam[1]),hx(cam[2]),
             hx(0.0),hx(0.0),hx(0.0), hx(210.0)))
    F("FC_FRONT", [(-50.0,-30.0,300.0),(50.0,-30.0,300.0),(0.0,30.0,300.0)])
    F("FC_BACK",  [(50.0,-30.0,300.0),(-50.0,-30.0,300.0),(0.0,30.0,300.0)])
    F("FC_EDGEON",[(-50.0,-30.0,300.0),(-50.0,30.0,300.0),(-50.0,0.0,400.0)])
    return "\n".join(L) + "\n"


def main():
    out = {
        "pg_corpus_raster.txt": raster(),
        "pg_corpus_edge.txt":   edge(),
        "pg_corpus_span.txt":   span(),
        "pg_corpus_proj.txt":   proj(),
    }
    import hashlib
    for name, text in out.items():
        path = os.path.join(HERE, name)
        with open(path, "w", newline="\n") as f:
            f.write(text)
        n = sum(1 for ln in text.splitlines()
                if ln.strip() and not ln.startswith("#"))
        print("%-24s %5d rows  sha256=%s"
              % (name, n, hashlib.sha256(text.encode()).hexdigest()[:16]))


if __name__ == "__main__":
    main()
