#!/usr/bin/env python3
"""fpmkbreak.py - build the deliberately broken variants.

House rule: every test builds a broken version of its subject and requires
that to fail.  A test that has never been seen to fail is not evidence.

The broken files are GENERATED from the good ones with one documented
substitution each, rather than written by hand, so that the only difference
between subject and break is the difference being tested.  A hand-written
break can accidentally differ in a second place and then "it failed" says
nothing about which break caused it.

  BREAK 1 - ENCODING.  fpx87bad.txt is fpx87.txt with FSub and FQuo
  emitting the REVERSED-OPERAND opcode.  DC A7 is `fsub qword` and DC AF
  is `fsubr qword`; DC B7 is `fdiv` and DC BF is `fdivr`.  One nibble.
  This is the single most likely way for a hand-typed x87 table to be
  wrong, it produces numbers rather than a crash, and on symmetric test
  vectors it can even look plausible.  Schedules 2 and 4 must fail.

  BREAK 2 - THE CAST RULE.  fpconvbad.txt is fpconv.txt with the fldcw
  bracket removed from FToIntChop, leaving a bare fistp.  Under the
  engine's RC=nearest that silently turns every C cast into a round to
  nearest, which is exactly the mistake the whole FToIntChop/FToIntNear
  split exists to prevent - and it is a SEED, so it is the expensive one.
  The int-chop column must fail; the int-near column must not.
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))


def rd(n):
    return open(os.path.join(HERE, n), encoding='latin-1').read()


def wr(n, s):
    open(os.path.join(HERE, n), 'w', encoding='latin-1', newline='\n').write(s)
    print('  %-18s %6d bytes' % (n, len(s)))


BANNER = ('      ( *** GENERATED BY fpmkbreak.py - DELIBERATELY BROKEN ***\n'
          '\n\t%s\n\n'
          '\tDo not fix this file.  It exists to fail. )\n\n')

print('deliberately broken variants:')

# ---- break 1: reversed-operand encodings -----------------------------
s = rd('fpx87.txt')
n = 0
s2, k = re.subn(r'DC A7 <dFB0', 'DC AF <dFB0', s)
n += k
s2, k = re.subn(r'DC B7 <dFB0', 'DC BF <dFB0', s2)
n += k
assert n == 2, 'expected exactly 2 substitutions, made %d' % n
s2 = BANNER % ('fpx87.txt with FSub emitting fsubr and FQuo emitting fdivr:\n'
               '\tDC A7 -> DC AF and DC B7 -> DC BF, one nibble each.\n'
               '\tSchedules 2 (FSub) and 4 (FQuo) must show differences;\n'
               '\tevery other schedule must still pass, because nothing\n'
               '\telse changed.') + s2
wr('fpx87bad.txt', s2)

# ---- break 2: the cast rule ------------------------------------------
s = rd('fpconv.txt')
good = '''"FToIntChop"
	[FCWCSAV] = 0;
	{
	    9B					(fwait)
	    D9 BF <dFCWCSAV mtp bytesperunit>	(fnstcw [edi+FCWCSAV*4])
	}
	A = [FCWCSAV]; A & 0F3FFh; A | 0C00h; [FCWCHOP] = A;
	{
	    D9 AF <dFCWCHOP mtp bytesperunit>	(fldcw [edi+FCWCHOP*4])
	    DD 87 <dFA0 mtp bytesperunit>	(fld   qword [edi+FA0*4])
	    DB 9F <dFI  mtp bytesperunit>	(fistp dword [edi+FI*4])
	    D9 AF <dFCWCSAV mtp bytesperunit>	(fldcw [edi+FCWCSAV*4])
	}
	end;'''
bad = '''"FToIntChop"
	( BROKEN: the fldcw bracket is gone.  This is a bare fistp under
	  whatever the ambient rounding control happens to be, which under
	  FEnter is nearest.  Every C cast silently becomes a round to
	  nearest and every generation seed is wrong. )
	{
	    DD 87 <dFA0 mtp bytesperunit>	(fld   qword [edi+FA0*4])
	    DB 9F <dFI  mtp bytesperunit>	(fistp dword [edi+FI*4])
	}
	end;'''
assert good in s, 'fpconv.txt FToIntChop no longer matches the pattern'
s2 = BANNER % ('fpconv.txt with the fldcw bracket removed from\n'
               '\tFToIntChop.  The "int chop" and "int16 chop" columns must\n'
               '\tshow differences; "int near" must NOT, because that route\n'
               '\tis untouched and was always meant to round to nearest.'
               ) + s.replace(good, bad)
wr('fpconvbad.txt', s2)

# ---- the two broken drivers ------------------------------------------
drv = rd('fptest.txt')
for name, sub, why in (
        ('fpbreakenc',
         [('\tfpx87;\n', '\tfpx87bad;\n')],
         'links fpx87bad: FSub is fsubr, FQuo is fdivr'),
        ('fpbreakchop',
         [('\tfpconv;\n', '\tfpconvbad;\n')],
         'links fpconvbad: FToIntChop has no fldcw bracket')):
    d = drv
    for a, b in sub:
        assert a in d
        d = d.replace(a, b)
    d = d.replace('program name = { fptest };',
                  'program name = { %s };' % name)
    d = d.replace('fptoutname = { fpout.bin };',
                  'fptoutname = { %sout.bin };' % name)
    d = BANNER % ('fptest.txt, but it %s.\n'
                  '\tRun it through fpdiff exactly as fptest is run.  If it\n'
                  '\tPASSES, the harness is not testing what it claims to.'
                  % why) + d
    wr(name + '.txt', d)
