"""GUARDS: the contract of the *% / *%' instruction that galaxy2.txt relies on
but, by its own shape, cannot test.

galaxy2.txt writes `A *% B; A + B;`. The add is commutative, so hi + lo equals
lo + hi and galaxy2.bin is blind to a transposition of the two halves: a *%
that put the high half in A and the low in B would pass test_galaxy.py
unchanged. Every other user of the instruction would then be silently wrong.
This file closes that axis by storing A and B SEPARATELY after the multiply.

Three properties are pinned:

  1. OPERAND ORDER AND VALUE.  a *% b  leaves the low 32 bits of the signed
     64-bit product in a and the high 32 bits in b; a *%' b does the same
     unsigned. Checked against arbitrary-precision Python over a table of
     boundary pairs: 0x80000000 squared, 0x80000000 x -1, -1 x -1,
     0x7FFFFFFF squared, and the operand shapes the galaxy hash produces.

  2. REGISTER DAMAGE.  galaxy2.txt names only A and B; it stores results
     through C and reads variables in between. C, D and E must come out of
     `A *% B` untouched - D especially, since the underlying imul writes edx
     and the pack has to push/pop around it.

  3. THE MEMORY FORM CLOBBERS ITS OPERAND.  `A *% [v]` writes the high half
     into the VARIABLE v. This is the documented reason galaxy2.txt uses the
     register x register form only: at both of its multiply sites the second
     operand is read again afterwards, so a memory form there would destroy
     live state. The test asserts the clobber so that the constraint in the
     source comment stays true rather than becoming folklore.

NEGATIVE CONTROLS, both computed from the reference and printed with counts:
a transposed contract would fail on most pairs, and the signed and unsigned
answers differ on most pairs - so neither check can be passing by coincidence.

HOW IT FAILS: a compiler or pack change that swaps the halves, drops the sign,
or stops preserving edx fails here loudly, and does so in one screen of output
that names the exact pair and the expected halves.

RUN: python tests/test_mulsplit.py
"""

import os
import struct
import sys

import linoharness as L


M32 = 0xFFFFFFFF
MIN32, MAX32 = 0x80000000, 0x7FFFFFFF

PAIRS = [
    (0, 0), (1, 1), (1, 0), (0, 1), (2, 3),
    (M32, M32), (M32, 1), (1, M32),
    (MIN32, MIN32), (MIN32, M32), (M32, MIN32),
    (MAX32, MAX32), (MAX32, MIN32), (MIN32, MAX32),
    (MIN32, 2), (2, MIN32), (MAX32, 2), (2, MAX32),
    (0x10000, 0x10000), (0x10001, 0x10000),
    (0xAAAAAAAA, 0x55555555), (0x55555555, 0xAAAAAAAA),
    (0xDEADBEEF, 0xCAFEBABE), (0xCAFEBABE, 0xDEADBEEF),
    (123456789, 987654321), (0xFFFF0000, 0x0000FFFF),
    # the operand shapes the galaxy hash actually produces
    ((-350000) & M32, (-600000) & M32),
    ((-600000) & M32, (-350000) & M32),
    (299950, 400000), (0x00030D40, 0x000186A0),
]

# 100000 * 70000 = 7000000000 = 0x1_A13B_8600 - a product that needs the high
# half, with sentinels chosen to look like nothing the multiply could produce.
REG_A, REG_B = 100000, 70000
SENTINEL_C, SENTINEL_D, SENTINEL_E = 0x0C0C0C0C, 0x0D0D0D0D, 0x0E0E0E0E


def s32(v):
    v &= M32
    return v - 0x100000000 if v & 0x80000000 else v


def split(a, b, signed):
    p = s32(a) * s32(b) if signed else (a & M32) * (b & M32)
    return p & M32, (p >> 32) & M32


# --------------------------------------------------------------- lino emitters

def emit_halves(path, progname, outname, op):
    o = ["\n      ( Generated by tests/test_mulsplit.py - do not edit. )\n"
         "      ( %s with the two halves kept apart, so low vs high is visible. )\n\n"
         % op]
    o.append('"directors"\n\n\tprogram name = { %s };\n\tunit = 32;\n\n' % progname)
    o.append('"constants"\n\n\tNPAIR\t= %d;\n\tPERPAIR\t= 4;\n\n' % len(PAIRS))
    o.append('"variables"\n\n\toutIdx\t= 0;\n\tpa\t= 0;\n\tpb\t= 0;\n\tlo\t= 0;\n\thi\t= 0;\n')
    o.append('\n\tresult file name = { %s };\n\n' % outname)
    o.append('"workspace"\n\n\tresults = NPAIR multiplied PERPAIR;\n\n')
    o.append('"programme"\n\n\t[outIdx] = 0;\n')
    for n, (a, b) in enumerate(PAIRS):
        o.append("\n\t( pair %d )\n" % n)
        o.append(L.setconst("pa", a))
        o.append(L.setconst("pb", b))
        o.append("\tA = [pa]; B = [pb]; A %s B;\t[lo] = A; [hi] = B;\n" % op)
        o.append("\tA = results; A + [outIdx];\n")
        o.append("\tC = [pa];  [A] = C;\n")
        o.append("\tA + 1; C = [pb]; [A] = C;\n")
        o.append("\tA + 1; C = [lo]; [A] = C;\n")
        o.append("\tA + 1; C = [hi]; [A] = C;\n")
        o.append("\tA = [outIdx]; A + PERPAIR;\t[outIdx] = A;\n")
    o.append(L.DUMP % {"units": "NPAIR multiplied PERPAIR"})
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("".join(o))


REGS_SRC = """
      ( Generated by tests/test_mulsplit.py - do not edit. )
      ( Does *%% damage the registers galaxy2.txt does not name, and does the
        memory form really write the high half over its operand? )

"directors"

\tprogram name = { tregs };
\tunit = 32;

"variables"

\tpa\t= 0;
\tpb\t= 0;
\tmemv\t= 0;

\toA\t= 0;
\toB\t= 0;
\toC\t= 0;
\toD\t= 0;
\toE\t= 0;
\tdlo\t= 0;
\tdmem\t= 0;

\tresult file name = { tregs.bin };

"workspace"

\tresults = 7;

"programme"

\t( register x register, with sentinels in the registers *% must not touch )

@@LOADA@@@@LOADB@@
\tA = [pa];
\tB = [pb];
\tC = 0; C + @@SC@@;
\tD = 0; D + @@SD@@;
\tE = 0; E + @@SE@@;

\tA *% B;

\t[oA] = A; [oB] = B; [oC] = C; [oD] = D; [oE] = E;

\t( direct form: does A *% [memv] overwrite memv itself? )

@@LOADM@@
\tA = 0; A + @@PA@@;
\tA *% [memv];
\t[dlo] = A;
\tA = [memv];\t\t\t[dmem] = A;

\tA = results;
\tC = [oA];   [A] = C;
\tA + 1; C = [oB];   [A] = C;
\tA + 1; C = [oC];   [A] = C;
\tA + 1; C = [oD];   [A] = C;
\tA + 1; C = [oE];   [A] = C;
\tA + 1; C = [dlo];  [A] = C;
\tA + 1; C = [dmem]; [A] = C;
"""


def emit_regs(path):
    # Token substitution rather than %-formatting: lino uses % as an operator
    # and *% is all over this source, so a stray "% m" would be read as a
    # format spec. @@TOKEN@@ cannot collide with anything the language spells.
    body = REGS_SRC
    for tok, val in (("@@LOADA@@", L.setconst("pa", REG_A)),
                     ("@@LOADB@@", L.setconst("pb", REG_B)),
                     ("@@LOADM@@", L.setconst("memv", REG_B)),
                     ("@@SC@@", str(SENTINEL_C)),
                     ("@@SD@@", str(SENTINEL_D)),
                     ("@@SE@@", str(SENTINEL_E)),
                     ("@@PA@@", str(REG_A))):
        body = body.replace(tok, val)
    assert "@@" not in body, "unsubstituted token in the register probe source"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body + L.DUMP % {"units": "7"})


# ------------------------------------------------------------------- the test

def check_halves(c, blob, signed, label):
    got = [struct.unpack_from("<4I", blob, i * 16) for i in range(len(blob) // 16)]
    if not c.eq(len(got), len(PAIRS), "%s returned one record per pair" % label):
        return
    bad, transposed_would_fail, sign_would_fail = [], 0, 0
    for i, (a, b) in enumerate(PAIRS):
        lo, hi = split(a, b, signed)
        want = (a & M32, b & M32, lo, hi)
        if got[i] != want:
            bad.append((i, a, b, got[i], want))
        if lo != hi:
            transposed_would_fail += 1
        if split(a, b, signed) != split(a, b, not signed):
            sign_would_fail += 1
    detail = ""
    if bad:
        i, a, b, g, w = bad[0]
        detail = ("%d/%d wrong, first pair %d: 0x%08X x 0x%08X -> got lo=0x%08X hi=0x%08X "
                  "want lo=0x%08X hi=0x%08X" % (len(bad), len(PAIRS), i, a, b, g[2], g[3], w[2], w[3]))
    c.ok(not bad, "%s: every pair matches the bignum reference in BOTH halves" % label, detail)
    c.ok(transposed_would_fail >= len(PAIRS) * 2 // 3,
         "  ...and a transposed low/high contract would have failed",
         "%d/%d pairs have low != high" % (transposed_would_fail, len(PAIRS)))
    c.ok(sign_would_fail >= len(PAIRS) // 2,
         "  ...and the opposite signedness would have failed",
         "%d/%d pairs differ signed vs unsigned" % (sign_would_fail, len(PAIRS)))


def main():
    c = L.Check("test_mulsplit - the *% contract galaxy2.txt cannot test itself")
    gen = L.gen_dir()

    for op, prog, signed in (("*%", "thalfs", True), ("*%'", "thalfu", False)):
        src = os.path.join(gen, prog + ".txt")
        emit_halves(src, prog, prog + ".bin", op)
        blob, exe, note = L.build_and_run(src, os.path.join(gen, prog + ".bin"),
                                          L.EXT_COMPILER, L.EXT_CPU)
        if c.ok(blob is not None, "%s program builds and runs" % op, note):
            check_halves(c, blob, signed, "%s over %d boundary pairs" % (op, len(PAIRS)))

    # ---------------------------------------------------------- registers
    src = os.path.join(gen, "tregs.txt")
    emit_regs(src)
    blob, exe, note = L.build_and_run(src, os.path.join(gen, "tregs.bin"),
                                      L.EXT_COMPILER, L.EXT_CPU)
    if c.ok(blob is not None, "register-damage probe builds and runs", note):
        oA, oB, oC, oD, oE, dlo, dmem = struct.unpack("<7I", blob)
        lo, hi = split(REG_A, REG_B, True)
        c.eq((oA, oB), (lo, hi),
             "A *%% B: %d x %d -> A=low B=high" % (REG_A, REG_B))
        c.eq((oC, oD, oE), (SENTINEL_C, SENTINEL_D, SENTINEL_E),
             "A *% B leaves C, D and E exactly as it found them")
        c.eq(dlo, lo, "memory form leaves the low half in A")
        c.eq(dmem, hi,
             "memory form OVERWRITES its variable operand with the high half "
             "- the documented reason galaxy2.txt uses register x register only")

    return c.done()


if __name__ == "__main__":
    sys.exit(main())
