"""GUARDS: the Wave 4 star-identity and system-generation port - and above
everything else, its DRAW ACCOUNTING.

WHAT IS BEING PROTECTED. A Noctis star system is generated by one seeded
stream of Borland rand() calls. NOCTIS-0.CPP:4059-4376 walks eight phases and
takes a number of draws that depends on the star class, on the planet count,
on planet types, and on while-loops with no iteration cap. Get one draw wrong
- take an extra, skip one, or take the right number in the wrong order - and
every value after it comes off a stream that has slipped by one. The result
is not noise. It is a complete, plausible, entirely wrong solar system, and
nothing about it looks broken. Draw accounting, not any individual formula,
is what this test exists to guard.

    nearstar_identity = x/100000 * y/100000 * z/100000     :4078  DOUBLE
    srand seed        = (long)x%10000 * (long)y%10000 * (long)z%10000
                                                           :4080  LONG
The two are different expressions and this test grades both: the identity
against the binary64 the 1996 file stores, the seed through the planet count
it produces.

THE ORACLES, AND WHY THEY ARE NOT CIRCULAR

  STARMAP.BIN   37,578 records charted by real players with the shipped 1996
                executable over about twenty years. Its 'S' records carry a
                star class in bytes 30..31, written as random(12) seeded from
                the identity; its 'P' records carry a body index. Nothing in
                this repository produced it or can change it.
  DL.EXE        the 1996 machine code's own stdout. The GOES module prints a
                star's charted bodies arranged by the LIVE values of
                nearstar_p_owner[] and nearstar_p_moonid[] - which is to say,
                it prints the answer to exactly the question this wave is
                asking. 122 captures, taken under DOSBox-X and re-captured
                byte-identical in a second session.
  two references ns_ref.c (a line-ordered transcription of the DOS source,
                arithmetic on the real x87) and ns_spec.py (built from the
                draw table outwards, exact Fraction arithmetic, Wave 1's
                pinned Python LCG). Both are rebuilt and re-run every run.
                Agreement between them and the port is reported as its own
                class: it is evidence about TRANSCRIPTION and nothing else.

NOTHING IS GRADED AGAINST A STORED EXPECTATION. The corpus is re-swept from
the galaxy hash and re-paired against STARMAP.BIN every run. gcc rebuilds the
C reference, the L.in.oleum compiler rebuilds the port, and no .nstopo checked
in anywhere is opened. work/ is never written to: every build happens in a
sandbox under tests/gen holding byte-identical copies. The one exception, said
plainly: the 122 DL.EXE captures are read off disk rather than re-taken,
because re-taking them opens a DOSBox-X window on the user's desktop. They are
an artifact of the 1996 program, like STARMAP.BIN, not an expectation of ours.

THE BREAKS. Seven single-edit sabotages of the port's own draw sequence -
one per phase, adding, removing and reordering - are built, run and graded
by every leg. Each must disagree with the references, each must be caught by
every leg that can be ARGUED to see it, and the 1996 artifacts must between
them catch most of the set. The test prints the whole matrix of what actually
caught what, because "which oracle is blind to which phase" is a result and
not an embarrassment. A grader that cannot fail is not a grader.

WHAT THIS TEST DOES NOT COVER, PLAINLY:

  * GEOMETRY IS OUT OF SCOPE, because the wave scoped it out. Wave 4 ported
    the TOPOLOGY - nop, nob, every body's type, owner and moonid, and the
    draw sequence - and deliberately discards the values of the eleven
    float-argument draw sites. p_orb_seed, p_tilt, p_orb_tilt, p_orb_ecc,
    p_ray, p_orb_ray, p_orb_orient, p_ring and key_radius are not computed
    by this port at all, so no check here says anything about them. Section
    2 pins the site registry at eleven so that the day geometry arrives, it
    arrives as a deliberate change that fails this test first.
  * THE FLOAT-TO-INT CAST BOUNDARY IS NOT CLOSED HERE. NsIdentChop16
    truncates a live, unstored extended value, and the catalogue cannot
    separate that from a chop of the stored binary64: both give the same
    seed on every record in the corpus. The CLASS leg below ranks chop
    against nothing finer, and no result in this file may be read as
    settling the question. (Wave 6 settled it elsewhere, out of NOCTIS.EXE's
    machine code - chop on the live 80-bit st(0), so NsIdentChop16's reading
    is the original's. That evidence is in test_geometry.py section 1 and
    docs-notes/OPENITEMS.md entry 1, not here.)
  * ONE PHASE IS INVISIBLE TO BOTH 1996 ORACLES. Section 9 measures it
    rather than asserting around it.
  * THE NSIN SEED OVERRIDE. Section 10 pins a known, bounded disagreement
    between the port and the references instead of avoiding it silently.

RUN: python tests/test_nearstar.py             (~3 min, needs gcc)
     python tests/test_nearstar.py --quick     (no sabotages: for iterating)
"""

import os
import re
import subprocess
import sys
import random as pyrandom

import linoharness as L
import nsdrive as D
import nsspec as R
import starmapspec as S

sys.path.insert(0, L.HARNESS)
import ns_corpus as C                                            # noqa: E402
import ns_diff as DIFF                                           # noqa: E402
import ns_spec as N                                              # noqa: E402

NSWEEP = 120          # class-override rows per class, on real coordinates

# Every draw site in prepare_nearstar, by NOCTIS-0.CPP line number. Written
# out here from the source rather than imported, so that a site quietly
# disappearing from the references cannot also disappear from the target.
SITES = (4082,
         4088, 4089, 4090, 4091, 4092, 4093, 4094, 4096, 4098, 4103,
         4112, 4113, 4114,
         4123, 4127, 4134, 4138,
         4148, 4152, 4153, 4161,
         4183, 4186, 4194, 4195, 4196, 4197, 4198, 4199, 4201,
         4213, 4214, 4238, 4255,
         4308, 4310, 4331, 4333,
         4348, 4354, 4358)


def gcc_ref(exe, src):
    p = subprocess.run(["gcc", "-O2", "-fwrapv", "-Wall", "-Wextra",
                        "-o", exe, src, "-lm"],
                       capture_output=True, text=True, encoding="utf-8",
                       errors="replace")
    return p.returncode == 0, ((p.stdout or "") + (p.stderr or "")).strip()


def main():
    quick = "--quick" in sys.argv
    c = L.Check("test_nearstar - star identity and system generation, "
                "graded by STARMAP.BIN and DL.EXE")
    if not c.ok(os.path.exists(S.CATALOGUE),
                "the real STARMAP.BIN is where the reference clone puts it",
                S.CATALOGUE):
        return c.done()

    # =================================================== 1. THE CORPUS
    corpus = C.build("dl")
    ncoord, badcoord = C.assert_exact_integers(corpus)
    st = corpus.stats
    c.note("corpus: %d star records accepted from the DL box, %d discarded "
           "for having more than one candidate sector"
           % (len(corpus.rows), st["multi_candidate_records"]))
    c.note("        %d of them carry at least one player-named planet"
           % st["stars_with_bodies"])
    c.ok(len(corpus.rows) > 3000,
         "the corpus is large enough to be sharp", "%d rows" % len(corpus.rows))
    c.eq(len(badcoord), 0,
         "every coordinate is an exact integer inside int32, so :4080's three "
         "(long) chops are the identity and the seed needs no __ftol "
         "(%d checked)" % ncoord)

    rows = D.combined_rows(corpus, NSWEEP)
    nreal = len(corpus.rows)
    c.note("NSIN: %d real stars with phase H on, then %d class-override rows "
           "(%d classes x %d of the same coordinates)"
           % (nreal, len(rows) - nreal, N.STAR_CLASSES, NSWEEP))

    sky = R.Sky()
    c.eq((sky.n, len(sky.pids)), (37578, 29999),
         "the catalogue decodes to the record and 'P' counts the port's "
         "nslabel.txt hard-codes as NSMAPRECS")

    # ============================== 2. THE SUBJECT, AND ITS SITE REGISTRY
    good = D.Driver("tnsgood")
    nedits, names = good.install()
    c.eq(nedits, 0, "the good sandbox applies no mutation")
    same = good.unmodified(names)
    c.eq(len(same), len(names),
         "all %d L.in.oleum sources in the sandbox are byte-identical to "
         "work/ - what gets compiled IS the delivered port" % len(names))

    with open(os.path.join(L.WORK, "nstopo.txt"), "r",
              encoding="utf-8", errors="replace") as fh:
        topo = fh.read()
    prog = topo.split('"programme"', 1)[1]
    nsite = len(re.findall(r"SITE \d+", prog))
    ndraw = prog.count("=> NsDrawOnly")
    nzdraw = prog.count("=> NsZDrawOnly")
    c.eq((nsite, ndraw, nzdraw), (11, 5, 6),
         "the discarded-value site registry is still exactly 11 sites, "
         "5 single draws and 6 zrandoms = 17 draws. A twelfth site, or one "
         "of these computed for real, is geometry arriving - which is a "
         "later wave and must fail here first")
    c.eq(prog.count("=> NsZRandom"), 4,
         "phase F still has exactly four zrandom(100) sites: two per planet "
         "and two per moon")

    # ==================================== 3. BUILD AND RUN THE PORT
    ok, msg = good.build()
    if not c.ok(ok, "the delivered port compiles from the sandbox copy", msg):
        return c.done()
    lino, diag, msg = good.run(rows, timeout=300)
    if not c.ok(lino is not None,
                "nsrun leaves a fresh nstopo.bin - the programme's own "
                "failure path withholds it, so its absence is a failure and "
                "never an empty result", msg):
        return c.done()
    c.note(msg)
    c.eq(len(lino), len(rows), "one NSTOPO record per NSIN record")

    if c.ok(diag is not None, "nsdiag.bin is present"):
        c.eq(diag[0], D.DIAG_MAGIC,
             "nsdiag magic is DEFACED, not the zero the failure path writes")
        c.eq(diag[1], len(rows), "nsdiag agrees on the record count")
        c.eq(diag[2], 0, "NO system exceeded the 100,000-draw budget")
        c.note("worst system used %d draws, %.2f%% of the budget"
               % (diag[3], 100.0 * diag[3] / 100000))
        c.eq((diag[4], diag[5]), (1202500, 1202496),
             "phase H read the whole 1996 catalogue less its 4-byte header")
        c.eq(diag[6], 29999, "...and compacted every 'P' record in it")
        c.eq(diag[7], 0x033F,
             "the x87 control word at the end is still 033Fh - 64-bit "
             "precision, round to nearest even, which is Wave 3's contract")

    # =========================== 4. THE TWO REFERENCES, REBUILT AND RERUN
    sides = {"lino": lino}
    cexe = os.path.join(good.dir, "nsref.exe")
    cout = os.path.join(good.dir, "refc.nstopo")
    built, cmsg = gcc_ref(cexe, os.path.join(L.HARNESS, "ns_ref.c"))
    if c.ok(built, "gcc rebuilds ns_ref.c with -fwrapv and no warnings",
            cmsg or "clean"):
        c.ok(not cmsg, "...and it compiled without a single diagnostic", cmsg)
        subprocess.run([cexe, good.nsin, cout], check=True)
        sides["C"] = N.read_nstopo(cout)[1]
    else:
        c.note("the C reference is SKIPPED: %s" % cmsg.splitlines()[:1])

    pyout = os.path.join(good.dir, "refpy.nstopo")
    p = subprocess.run([sys.executable, os.path.join(L.HARNESS, "ns_spec.py"),
                        good.nsin, pyout], capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    if c.ok(p.returncode == 0, "the Python reference runs over the same NSIN",
            (p.stdout or "") + (p.stderr or "")):
        sides["python"] = N.read_nstopo(pyout)[1]

    nfield = 100
    for a in sorted(sides):
        for b in sorted(sides):
            if a >= b:
                continue
            bad = [i for i in range(len(rows)) if sides[a][i] != sides[b][i]]
            detail = ""
            if bad:
                i = bad[0]
                f = [k for k in range(nfield)
                     if sides[a][i][k] != sides[b][i][k]]
                detail = ("%d/%d records differ, first at %d in field(s) %s"
                          % (len(bad), len(rows), i, f[:6]))
            c.ok(not bad,
                 "TRANSCRIPTION: %s == %s on all %d fields of all %d records"
                 % (a, b, nfield, len(rows)), detail)
    c.ok(len(sides) == 3,
         "all three implementations were available - two agreeing is weaker "
         "evidence than three", "sides: %s" % ", ".join(sorted(sides)))

    # ============================ 5. DRAW-SITE COVERAGE, FROM THE LEDGER
    # A comparison that never reaches a site proves nothing about it. The C
    # reference emits (site, argument, value) for every draw; the sweep block
    # is replayed through it and every documented site must appear.
    if "C" in sides:
        swin = os.path.join(good.dir, "sweep.nsin")
        sout = os.path.join(good.dir, "sweep.nstopo")
        sled = os.path.join(good.dir, "sweep.nsled")
        N.write_nsin(swin, rows[nreal:])
        subprocess.run([cexe, swin, sout, "--ledger", sled], check=True)
        seen = {}
        for _k, draws in DIFF.read_ledger(sled):
            for site, _arg, _val in draws:
                seen[site] = seen.get(site, 0) + 1
        missing = [s for s in SITES if s not in seen]
        extra = [s for s in sorted(seen) if s not in SITES]
        c.ok(not missing and not extra,
             "every one of the %d draw sites in NOCTIS-0.CPP:4059-4376 is "
             "exercised by this corpus, and no site outside the list is"
             % len(SITES),
             "missing %s extra %s" % (missing, extra) if (missing or extra)
             else "%d draws over %d systems"
             % (sum(seen.values()), len(rows) - nreal))
    else:
        c.ok(False, "DRAW-SITE COVERAGE cannot be measured without the C "
             "reference's ledger - the corpus is unproven at every site")

    # =================================== 6. THE STRUCTURAL DRAW AUDIT
    bad = R.audit(lino)
    for label, _fn in R.AUDIT:
        hits = bad.get(label, [])
        c.ok(not hits,
             "DRAW AUDIT: %s" % label,
             "" if not hits else "%d records violate it, first %r"
             % (len(hits), hits[0]))
    # The draw table itself, recomputed and printed rather than remembered.
    # docs-notes/WAVE4_NEARSTAR.md quotes these numbers; this is where they
    # come from, and they are re-derived from the port's own counters on
    # every run rather than copied forward.
    c.note("")
    c.note("  the draw table, over %d systems" % len(lino))
    c.note("  %-8s %12s %8s %11s" % ("phase", "draws", "max", "systems>0"))
    for p in range(8):
        col = [r[12 + p] for r in lino]
        c.note("  %-8s %12d %8d %11d"
               % (N.PHASES[p], sum(col), max(col), sum(1 for v in col if v)))
    tot = [r[11] for r in lino]
    c.note("  %-8s %12d %8d %11d  (mean %.1f)"
           % ("total", sum(tot), max(tot), len(tot), sum(tot) / float(len(tot))))
    c.note("")

    # Every invariant above must be shown to have teeth. A hand-built record
    # that satisfies all ten, then one perturbation per invariant, each of
    # which must be flagged BY NAME.
    c.eq(R.audit([R.base_record()]), {},
         "CONTROL: the hand-built reference record satisfies all %d "
         "invariants" % len(R.AUDIT))
    c.eq(len(R.AUDIT_BREAKS), len(R.AUDIT),
         "...and there is one deliberate violation per invariant")
    for label, make in R.AUDIT_BREAKS:
        flagged = R.audit([make()])
        c.ok(label in flagged,
             "CONTROL: the audit flags a violation of %r by name" % label,
             "flagged instead: %s" % sorted(flagged) if label not in flagged
             else "")

    # ==================================== 7. THE CATALOGUE, RECOMPUTED
    g = R.grade(lino[:nreal], corpus.rows, sky)
    c.eq(len(g["coord_bad"]), 0,
         "every graded record carries back the coordinates it was given")
    c.eq(len(g["class_miss"]), 0,
         "CLASS: srand(chop(identity)); random(12) reproduces the 'S' tail "
         "of every one of the %d player-named records (%d placeholder "
         "record(s) excluded, and that count is printed so the exclusion "
         "cannot grow quietly)" % (g["class_tot"], g["placeholders"]))
    c.eq(g["ident_hit"], g["ident_tot"],
         "IDENTITY: the computed identity is BIT-IDENTICAL to the binary64 "
         "the 1996 file stores, on all %d records" % g["ident_tot"])
    c.eq(len(g["nob_viol"]), 0,
         "NOB: no player ever named a body the model does not generate, over "
         "%d systems carrying charted bodies" % g["nob_tot"])
    c.ok(g["nob_pinned"] > 1000,
         "...and on %d of them the highest charted index lands EXACTLY on "
         "nob, which pins the count rather than bounding it"
         % g["nob_pinned"], "%d systems" % g["nob_pinned"])
    c.eq((g["c6_named"], g["c6_modelled"]), (0, 0),
         "CLASS6: class_planets[6] is 0, so a class-6 star can have no body "
         "- and %d catalogued class-6 stars have none named and none "
         "modelled" % g["c6_stars"])
    # This leg grades search_id_code - the binary64 add, the strict window,
    # the key map - over every labelled body. It recounts with the port's OWN
    # nob, so it does not independently constrain nob; NOB above does that.
    c.eq(len(g["h_dis"]), 0,
         "PHASE H: nearstar_labeled agrees with an independent recount of "
         "the catalogue on all %d systems (%d labelled bodies)"
         % (g["h_agree"], g["h_bodies"]))

    # the controls: each leg must be able to fail
    tags = [r[5] for r in corpus.rows]
    rng = pyrandom.Random(20260805)
    perm = tags[:]
    rng.shuffle(perm)
    gp = R.grade(lino[:nreal], corpus.rows, sky, tag_perm=perm)
    frac = 100.0 * gp["class_hit"] / max(gp["class_tot"], 1)
    c.ok(frac < 25.0,
         "CONTROL: with the class tags permuted across records the CLASS leg "
         "collapses to chance - it is scoring arithmetic, not scoring "
         "'a number came out'",
         "%d/%d = %.2f%% (chance is 1/12 = 8.3%%)"
         % (gp["class_hit"], gp["class_tot"], frac))

    flipped = [list(r) for r in lino[:nreal]]
    for r in flipped:
        r[9] ^= 1
    gf = R.grade(flipped, corpus.rows, sky)
    c.eq(gf["ident_hit"], 0,
         "CONTROL: one flipped bit in the last place of the identity and the "
         "IDENTITY leg scores zero - it is an exact comparison")

    shrunk = [list(r) for r in lino[:nreal]]
    for r in shrunk:
        r[6] = max(r[6] - 1, 0)
    gs = R.grade(shrunk, corpus.rows, sky)
    c.ok(len(gs["nob_viol"]) > 500,
         "CONTROL: nob reduced by one and the NOB leg reports violations - "
         "the bound is tight, not slack",
         "%d violations" % len(gs["nob_viol"]))
    c.ok(len(gs["h_dis"]) > 500,
         "CONTROL: the same shrink is caught by PHASE H independently",
         "%d systems disagree" % len(gs["h_dis"]))

    # =========================== 8. DL.EXE, THE 1996 MACHINE CODE
    dlrows, dlok = None, False
    try:
        import ns_dl as DL
        dlrows = DL.capture_rows()
    except SystemExit as e:
        c.note("DL leg SKIPPED: %s" % e)
    if dlrows:
        dlin = [(x, y, z, -1, -1, -1, 0, 0)
                for (_c, _n, x, y, z, _cl) in dlrows]
        _r, _d, dmsg = good.run(dlin, timeout=120)
        tot, hit, fails = DL.grade(good.out, dlrows, verbose=False)
        dlok = tot > 0 and hit == tot
        c.ok(dlok,
             "DL: the port reproduces every one of the %d owner/moonid "
             "constraints the 1996 executable printed, over %d captures"
             % (tot, len(dlrows)),
             "%d/%d, first miss %r" % (hit, tot, fails[:1]) if not dlok
             else "")

    if quick:
        c.note("")
        c.note("--quick: the seven sabotages were NOT run, so nothing above "
               "has been shown to be able to fail. Do not read a --quick "
               "pass as a pass.")
        return c.done()

    # ============================================= 9. THE BREAKS
    c.note("")
    c.note("  the sabotages: one edit each, to the port's own draw sequence")
    c.note("  %-8s %-6s %-5s %s" % ("break", "phase", "kind", "caught by"))
    brk = D.Driver("tnsbrk")
    refname = "C" if "C" in sides else "python"
    if refname not in sides:
        c.ok(False, "no reference implementation survived, so the sabotages "
             "cannot be graded against one")
        return c.done()
    ref = sides[refname]
    matrix = []
    for mut in D.MUTATIONS:
        brk.mut = mut
        nedits, _names = brk.install()
        if not c.ok(nedits == len(mut.edits),
                    "BREAK %s edits the source it claims to" % mut.name,
                    "%d edit(s)" % nedits):
            continue
        ok, msg = brk.build()
        if not c.ok(ok, "BREAK %s compiles - it is wrong, not broken"
                    % mut.name, msg):
            continue
        mrec, mdiag, msg = brk.run(rows, timeout=300)
        if not c.ok(mrec is not None, "BREAK %s runs" % mut.name, msg):
            continue

        caught = set()
        nd = sum(1 for i in range(len(rows)) if mrec[i][11] != ref[i][11])
        nt = sum(1 for i in range(len(rows)) if mrec[i] != ref[i])
        if nt:
            caught.add("refs")
        if R.audit(mrec):
            caught.add("audit")
        mg = R.grade(mrec[:nreal], corpus.rows, sky)
        ncat = (len(mg["class_miss"]) + len(mg["nob_viol"]) + len(mg["h_dis"])
                + mg["c6_named"] + mg["c6_modelled"] + len(mg["ident_miss"]))
        if ncat:
            caught.add("catalogue")
        dlscore = ""
        if dlrows:
            brk.run([(x, y, z, -1, -1, -1, 0, 0)
                     for (_c, _n, x, y, z, _cl) in dlrows], timeout=120)
            dtot, dhit, _f = DL.grade(brk.out, dlrows, verbose=False)
            if dhit != dtot:
                caught.add("dl")
            dlscore = " dl %d/%d" % (dhit, dtot)

        c.note("  %-8s %-6s %-5s %s" % (mut.name, mut.phase, mut.kind,
                                        ",".join(sorted(caught)) or "NOTHING"))
        matrix.append((mut, caught, nd, nt, ncat, dlscore))

        c.ok("refs" in caught,
             "BREAK %-6s must disagree with the reference recomputed this "
             "run: %s"
             % (mut.name, mut.blurb),
             "%d/%d records changed their draw count, %d changed at all%s"
             % (nd, len(rows), nt, dlscore))
        c.eq(caught & mut.must, mut.must,
             "BREAK %-6s is caught by every leg that can be ARGUED to see it "
             "(%s)" % (mut.name, ",".join(sorted(mut.must))))
        c.ok(nd > 0,
             "BREAK %-6s moves a DRAW COUNT on some system, which is the "
             "thing this test exists to guard" % mut.name,
             "%d of %d systems" % (nd, len(rows)))

    c.eq(len(matrix), len(D.MUTATIONS), "every sabotage was built and graded")

    # Aggregate power of the two 1996 artifacts, measured over the whole set
    # rather than asserted per break. Six of the seven sabotages land in a
    # phase whose values reach a type, an owner or a moon id; those must be
    # visible to a file and a binary from 1996, or this test is grading
    # itself.
    ncat = sum(1 for (_m, s, _a, _b, _c, _d) in matrix if "catalogue" in s)
    ndl = sum(1 for (_m, s, _a, _b, _c, _d) in matrix if "dl" in s)
    c.ok(ncat >= 5, "STARMAP.BIN alone catches at least 5 of the %d sabotages"
         % len(matrix), "%d caught" % ncat)
    if dlrows:
        c.ok(ndl >= 5, "DL.EXE alone catches at least 5 of the %d sabotages"
             % len(matrix), "%d caught" % ndl)
    c.ok(all("refs" in s for (_m, s, _a, _b, _c, _d) in matrix),
         "and the reference comparison catches all %d" % len(matrix))

    # The honest measurement, pinned rather than argued. Phase G is the last
    # drawing phase; its values reach only p_ring, and every later rand() user
    # in the original re-seeds first (NOCTIS-1.CPP:1975, 2052, 2642, 2796,
    # 3171, 3225). So a spurious draw there is invisible to both 1996
    # artifacts - by construction, not by a weakness of the harness. It is
    # caught here by the per-phase counters and by the two references, and
    # this test records that the external oracles did NOT see it rather than
    # letting the pass rate imply they did.
    for (mut, caught, _nd, _nt, _ncat, dls) in matrix:
        if mut.name == "gadd":
            c.ok("catalogue" not in caught and "dl" not in caught,
                 "MEASURED, NOT A POLICY: the phase-G sabotage is invisible "
                 "to BOTH 1996 oracles%s. It is caught only by the per-phase "
                 "counters and by the references, which is why r12..r19 are "
                 "load-bearing evidence in this port and not diagnostics"
                 % dls,
                 "caught by %s" % ",".join(sorted(caught)))

    # ==================== 10. THE KNOWN DIVERGENCE, PINNED NOT AVOIDED
    # An NSIN seed override reaches starnop() in the port and does not in the
    # references. Both readings are defensible and the spec does not choose.
    # Rather than steer around it, pin it: the disagreement must be confined
    # to field r7 and to override rows, and must never appear anywhere else.
    ovr = [(0, 0, 0, cl, sd, -1, 0, 0)
           for cl in range(N.STAR_CLASSES) for sd in (0, 1, 7, 999, 54321)]
    orec, _d, omsg = good.run(ovr, timeout=120)
    if c.ok(orec is not None, "the port runs the seed-override rows", omsg):
        oout = os.path.join(good.dir, "ovr.nstopo")
        p = subprocess.run([sys.executable,
                            os.path.join(L.HARNESS, "ns_spec.py"),
                            good.nsin, oout], capture_output=True, text=True,
                           encoding="utf-8", errors="replace")
        if not c.ok(p.returncode == 0,
                    "the Python reference runs the same override rows",
                    (p.stdout or "") + (p.stderr or "")):
            return c.done()
        oref = N.read_nstopo(oout)[1]
        flds = set()
        for i in range(len(ovr)):
            flds |= {k for k in range(100) if orec[i][k] != oref[i][k]}
        c.eq(flds, {7},
             "KNOWN DIVERGENCE, pinned: with an NSIN seed override the port "
             "and the references disagree on field r7 (starnop) and on "
             "NOTHING ELSE. The override's scope over starnop is unsettled; "
             "this test bounds the disagreement instead of hiding it, and "
             "the graded corpus above uses no seed override")

    return c.done()


if __name__ == "__main__":
    sys.exit(main())
