"""GUARDS: the register-damage contract of the Mul64u / Mul64s interface - what
a caller is allowed to still be holding when it calls a 64-bit multiply.

The three backends are meant to be interchangeable, and the whole argument that
the port commits to none of them rests on that. Interchangeable means more than
"same answer": it means same damage. Two of them are pure L.in.oleum-visible
code, but mul64frag reaches the high half through `{ F7 EB }`, which writes edx
BEHIND the compiler's back - D is damaged by a fragment the register allocator
cannot see. If a future backend quietly started using C or E as scratch, every
caller holding a value there would be corrupted, the arithmetic would still be
bit-exact, and every other test in this suite would still pass.

MEASURED, NOT ASSUMED. The three source files disagreed with the documentation
and with each other about this: docs-notes/sitecount.md said "both destroy
A, B, C, D", mul64limb.txt and mul64star.txt said "Destroys A, B", and only
mul64frag.txt said "A, B, D". Two of those three cannot be right. This probe
puts sentinels in C, D and E, calls both entry points on each backend, and reads
the sentinels back, so the contract is a measurement.

What is pinned:

  * C and E survive every backend, at both entry points. That is the guarantee
    callers may rely on, and it is the one that would break silently.
  * whatever damage a backend does among C, D and E is a SUBSET of what its own
    header comment declares it destroys. This is what keeps the comment honest
    without pinning its wording: adding a clobber forces updating the sentence,
    and a stale sentence fails the build of trust rather than the reader's
    attention. Today frag declares A, B, D and damages D; limb and star declare
    A, B and damage neither C, D nor E.
  * all three still compute the same 64-bit product for the probe's operands,
    at both signednesses - so a "preserved" register cannot be preserved by a
    backend that has stopped working.

NEGATIVE CONTROL: a fourth backend, mul64frag with `C = 0; E = 0;` spliced into
both entry points, is built and run through the same probe. It must be caught
damaging exactly C and E. Without that, "C and E are preserved" could be a
sentence about a probe that cannot see registers at all.

Nothing under work/ is written. The probe and the backend copies live in
tests/gen.

HOW IT FAILS: the failing check names the register, the backend, the entry
point, the sentinel that went in and the value that came out.

RUN: python tests/test_mul64clobber.py
"""

import os
import re
import shutil
import struct
import sys

import linoharness as L


M32 = 0xFFFFFFFF

# Operands with a non-zero high half in both signednesses, and a high half that
# differs between them (0x9ABCDEF0 has bit 31 set), so a probe that confused the
# two entry points could not pass.
PA, PB = 0x12345678, 0x9ABCDEF0

# Values no plausible product or address could be mistaken for.
SENT_C, SENT_D, SENT_E = 0x0C0C0C0C, 0x0D0D0D0D, 0x0E0E0E0E

BACKENDS = [
    ("frag", "mul64frag.txt", L.STOCK_COMPILER, L.STOCK_CPU),
    ("limb", "mul64limb.txt", L.STOCK_COMPILER, L.STOCK_CPU),
    ("star", "mul64star.txt", L.EXT_COMPILER, L.EXT_CPU),
]

PROBE = """
      ( Generated by tests/test_mul64clobber.py - do not edit. )
      ( Sentinels in C, D and E across both Mul64 entry points, so the
        register damage of a backend is a measurement rather than a comment. )

"libraries"

\tmul64be;

"directors"

\tprogram name = { tclobber };
\tunit = 32;

"variables"

\tpa\t= 0;
\tpb\t= 0;

\tuA\t= 0;
\tuB\t= 0;
\tuC\t= 0;
\tuD\t= 0;
\tuE\t= 0;
\tulo\t= 0;
\tuhi\t= 0;

\tsA\t= 0;
\tsB\t= 0;
\tsC\t= 0;
\tsD\t= 0;
\tsE\t= 0;
\tslo\t= 0;
\tshi\t= 0;

\tresult file name = { tclobber.bin };

"workspace"

\tresults = 14;

"programme"

@@LOADA@@@@LOADB@@
\t( unsigned entry point )

\tC = [pa];\t[m64a] = C;
\tC = [pb];\t[m64b] = C;
\tC = 0; C + @@SC@@;
\tD = 0; D + @@SD@@;
\tE = 0; E + @@SE@@;

\t=> Mul64u;

\t[uA] = A; [uB] = B; [uC] = C; [uD] = D; [uE] = E;
\tA = [m64lo];\t[ulo] = A;
\tA = [m64hi];\t[uhi] = A;

\t( signed entry point, sentinels reloaded )

\tC = [pa];\t[m64a] = C;
\tC = [pb];\t[m64b] = C;
\tC = 0; C + @@SC@@;
\tD = 0; D + @@SD@@;
\tE = 0; E + @@SE@@;

\t=> Mul64s;

\t[sA] = A; [sB] = B; [sC] = C; [sD] = D; [sE] = E;
\tA = [m64lo];\t[slo] = A;
\tA = [m64hi];\t[shi] = A;

\tA = results;
\tC = [uA];\t[A] = C;
\tA + 1; C = [uB];\t[A] = C;
\tA + 1; C = [uC];\t[A] = C;
\tA + 1; C = [uD];\t[A] = C;
\tA + 1; C = [uE];\t[A] = C;
\tA + 1; C = [ulo];\t[A] = C;
\tA + 1; C = [uhi];\t[A] = C;
\tA + 1; C = [sA];\t[A] = C;
\tA + 1; C = [sB];\t[A] = C;
\tA + 1; C = [sC];\t[A] = C;
\tA + 1; C = [sD];\t[A] = C;
\tA + 1; C = [sE];\t[A] = C;
\tA + 1; C = [slo];\t[A] = C;
\tA + 1; C = [shi];\t[A] = C;
"""


def s32(v):
    v &= M32
    return v - 0x100000000 if v & 0x80000000 else v


def product(a, b, signed):
    p = (s32(a) * s32(b)) if signed else ((a & M32) * (b & M32))
    p &= 0xFFFFFFFFFFFFFFFF
    return p & M32, (p >> 32) & M32


def emit_probe(path):
    body = PROBE
    for tok, val in (("@@LOADA@@", L.setconst("pa", PA)),
                     ("@@LOADB@@", L.setconst("pb", PB)),
                     ("@@SC@@", str(SENT_C)),
                     ("@@SD@@", str(SENT_D)),
                     ("@@SE@@", str(SENT_E))):
        body = body.replace(tok, val)
    assert "@@" not in body, "unsubstituted token in the clobber probe"
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body + L.DUMP % {"units": "14"})


def declared_damage(path):
    """The registers a backend's own comments say it destroys."""
    with open(path, encoding="latin-1") as fh:
        text = fh.read()
    regs = set()
    for m in re.finditer(r"Destroys\s+([A-E](?:\s*,\s*[A-E])*)", text):
        regs |= {r.strip() for r in m.group(1).split(",")}
    return regs


def run_probe(name, backend_path, compiler, cpu, gen):
    shutil.copyfile(backend_path, os.path.join(gen, "mul64be.txt"))
    src = os.path.join(gen, "tclobber.txt")
    emit_probe(src)
    blob, exe, note = L.build_and_run(src, os.path.join(gen, "tclobber.bin"),
                                      compiler, cpu)
    if blob is None or len(blob) != 56:
        return None, note
    v = struct.unpack("<14I", blob)
    return {"u": dict(zip(("A", "B", "C", "D", "E", "lo", "hi"), v[:7])),
            "s": dict(zip(("A", "B", "C", "D", "E", "lo", "hi"), v[7:]))}, note


def check_one(c, name, res, declared):
    sentinels = {"C": SENT_C, "D": SENT_D, "E": SENT_E}
    damaged = set()
    for entry, label in (("u", "Mul64u"), ("s", "Mul64s")):
        got = res[entry]
        lo, hi = product(PA, PB, entry == "s")
        c.ok((got["lo"], got["hi"]) == (lo, hi),
             "  %s/%s computes 0x%08X x 0x%08X correctly" % (name, label, PA, PB),
             "got lo=0x%08X hi=0x%08X want lo=0x%08X hi=0x%08X"
             % (got["lo"], got["hi"], lo, hi))
        for reg, sent in sentinels.items():
            if got[reg] != sent:
                damaged.add(reg)
        for reg in ("C", "E"):
            c.ok(got[reg] == sentinels[reg],
                 "  %s/%s leaves %s untouched" % (name, label, reg),
                 "sentinel 0x%08X came back 0x%08X" % (sentinels[reg], got[reg]))

    c.ok(damaged <= declared,
         "  %s damages only what its header declares" % name,
         "measured %s, declared %s"
         % (sorted(damaged) or ["none"], sorted(declared)))
    return damaged


def main():
    c = L.Check("test_mul64clobber - the register contract of the Mul64 interface")
    gen = L.gen_dir()

    all_damage = {}
    for name, fname, compiler, cpu in BACKENDS:
        path = os.path.join(L.WORK, fname)
        declared = declared_damage(path)
        if not c.ok("A" in declared and "B" in declared,
                    "%s declares that it destroys A and B" % name,
                    "declared %s" % sorted(declared)):
            continue
        res, note = run_probe(name, path, compiler, cpu, gen)
        if not c.ok(res is not None,
                    "clobber probe builds and runs on the %s backend" % name, note):
            continue
        all_damage[name] = check_one(c, name, res, declared)

    if len(all_damage) == len(BACKENDS):
        union = set().union(*all_damage.values())
        c.note("measured damage beyond A and B: %s"
               % ", ".join("%s=%s" % (k, sorted(v) or "none")
                           for k, v in sorted(all_damage.items())))
        c.ok(union <= {"D"},
             "across all three backends the damage beyond A and B is at most D",
             "union %s" % (sorted(union) or ["none"]))

    # ---------------------------------------------------- negative control
    with open(os.path.join(L.WORK, "mul64frag.txt"), encoding="latin-1") as fh:
        frag = fh.read()
    assert frag.count("[m64hi] = D;") == 2
    wrecker = os.path.join(gen, "mul64wreck.txt")
    with open(wrecker, "w", encoding="utf-8") as fh:
        fh.write(frag.replace("[m64hi] = D;", "C = 0;\n\tE = 0;\n\t[m64hi] = D;"))
    res, note = run_probe("wreck", wrecker, L.STOCK_COMPILER, L.STOCK_CPU, gen)
    if c.ok(res is not None,
            "NC a backend that scribbles on C and E builds and runs - the "
            "arithmetic is untouched and nothing complains", note):
        lo, hi = product(PA, PB, False)
        c.ok((res["u"]["lo"], res["u"]["hi"]) == (lo, hi),
             "NC ...and it still returns the right product, so only the "
             "register damage distinguishes it")
        wrecked = {r for r in ("C", "D", "E")
                   if res["u"][r] != {"C": SENT_C, "D": SENT_D, "E": SENT_E}[r]}
        c.eq(sorted(wrecked), ["C", "D", "E"],
             "NC ...and the probe catches it: C and E clobbered, D as ever")

    for stale in (os.path.join(gen, "mul64be.txt"), wrecker):
        if os.path.exists(stale):
            os.remove(stale)

    return c.done()


if __name__ == "__main__":
    sys.exit(main())
