"""Generate work/probe_w1_arith.txt - a straight-line lino probe that answers
the Wave 1 instruction-semantics questions empirically.

Sections, in slot order:
  M  multiply : signed '*' low 32, unsigned "'*" low 32              (2 units/case)
  S  shift    : s>16, s>>16, (s>16)&7FFF, (s>>16)&7FFF, s&FFFF, sx16 (6 units/case)
  D  divide   : v/32768, v '/ 32768, v>>15, v>15                     (4 units/case)
"""
import os, struct

M32 = 0xFFFFFFFF
LCG = 0x015A4E35

MUL_CASES = [
    (LCG, 1),
    (1, LCG),
    (0x12345678, LCG),
    (0xFFFFFFFF, LCG),
    (0x80000000, LCG),
    (0x7FFFFFFF, 0x7FFFFFFF),
    (0xDEADBEEF, 0xCAFEBABE),
    (0x0000FFFF, 0x00010001),
    (0x0000FFFF, LCG),
    (0x9E3779B9, 0x85EBCA6B),
    (0xFFFF0000, LCG),
    (2, 0x80000000),
]

SHIFT_CASES = [
    0x00000001, 0x12345678, 0x7FFFFFFF, 0x80000000,
    0xFFFFFFFF, 0x89ABCDEF, 0xC0000000, 0xFFFF0000,
    0x8000FFFF, 0x0001ABCD,
]

def s32(u):
    u &= M32
    return u - 0x100000000 if u & 0x80000000 else u

DIV_CASES = [
    32767 * 32767,
    s32(-32767 * 32767) & M32,
    12345 * 1000,
    s32(-12345 * 1000) & M32,
    1, M32,            # 1 and -1
    32768, 32767,
    s32(-32768) & M32, s32(-32769) & M32,
    0x7FFFFFFF, 0x80000000,
    s32(12345 * -1000) & M32,
    s32(-1) & M32,
]

def setconst(reg, uval):
    uval &= M32
    if uval < 0x80000000:
        return "\t%s = 0; %s + %d;\n" % (reg, reg, uval)
    neg = 0x100000000 - uval
    if neg <= 2147483647:
        return "\t%s = 0; %s - %d;\n" % (reg, reg, neg)
    return "\t%s = 0; %s - 2147483647; %s - 1;\n" % (reg, reg, reg)

def store(idx):
    # value is in A; stash it, then write it into results[idx]
    return ("\t[t] = A;\n"
            "\tA = results; A + %d; C = [t]; [A] = C;\n" % idx)

out = []
labels = []
idx = 0

out.append("""      ( *** probe w1 arith - L.in.oleum instruction semantics for the
            Borland LCG.  Generated by scratchpad/genarith.py.  Straight-line,
            no loops: every case is unrolled so a wrong answer is a wrong
            slot, not a wrong control flow. *** )

"directors"

\tprogram name = { probew1arith };
\tunit = 32;

"variables"

\tt = 0;
\tresult file name = { probew1arith.bin };

"workspace"

\tresults = %d;

"programme"
""")

body = []

body.append("\n\t( ---- section M: 32x32 -> low 32 multiply ---- )\n")
for (x, y) in MUL_CASES:
    body.append("\n\t( %08X * %08X )\n" % (x, y))
    body.append(setconst("A", x)); body.append(setconst("B", y))
    body.append("\tA * B;\n"); body.append(store(idx))
    labels.append(("M.signed", x, y)); idx += 1
    body.append(setconst("A", x)); body.append(setconst("B", y))
    body.append("\tA '* B;\n"); body.append(store(idx))
    labels.append(("M.unsigned", x, y)); idx += 1

body.append("\n\t( ---- section S: shift right and mask ---- )\n")
for s in SHIFT_CASES:
    body.append("\n\t( seed %08X )\n" % s)
    for name, code in (
        ("S.shr16",      "\tA > 16;\n"),
        ("S.sar16",      "\tA >> 16;\n"),
        ("S.shr16mask",  "\tA > 16; A & 7FFFh;\n"),
        ("S.sar16mask",  "\tA >> 16; A & 7FFFh;\n"),
        ("S.low16",      "\tA & FFFFh;\n"),
        ("S.sx16",       "\tA & FFFFh; A # 8000h; A - 8000h;\n"),
    ):
        body.append(setconst("A", s)); body.append(code); body.append(store(idx))
        labels.append((name, s, None)); idx += 1

body.append("\n\t( ---- section D: divide by 32768 ---- )\n")
for v in DIV_CASES:
    body.append("\n\t( value %08X )\n" % v)
    for name, code in (
        ("D.sdiv", "\tB = 0; B + 32768; A / B;\n"),
        ("D.udiv", "\tB = 0; B + 32768; A '/ B;\n"),
        ("D.sar15", "\tA >> 15;\n"),
        ("D.shr15", "\tA > 15;\n"),
    ):
        body.append(setconst("A", v)); body.append(code); body.append(store(idx))
        labels.append((name, v, None)); idx += 1

NSLOTS = idx
out[0] = out[0] % NSLOTS
out.extend(body)

out.append("""
\t[File Name]\t= result file name;
\t[File Position] = 0;
\t[File Command]\t= WRITE;
\t[Block Pointer] = results;
\t[Block Size]\t= %d;
\t[Block Size]\t* BYTES PER UNIT;
\tisocall;

\t[File Name]\t= result file name;
\t[File Position] = 0;
\t[File Command]\t= SET SIZE;
\t[File Size]\t= %d;
\t[File Size]\t* BYTES PER UNIT;
\tisocall;

\tend;
""" % (NSLOTS, NSLOTS))

src = os.path.join(r"C:\programmieren\linoleum\work", "probe_w1_arith.txt")
with open(src, "w") as fh:
    fh.write("".join(out))

import json
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "probe_w1_arith_labels.json"), "w") as fh:
    json.dump(labels, fh)

print("wrote", src, NSLOTS, "slots")
