"""gentest2.py - semantically validate ALL 121 MUL-split patterns.

Extends the register-only test to every operand configuration, including the
memory forms, still without modifying any part of the toolchain.

The memory patterns carry D1.4 / D2.4 placeholders that the compiler normally
fills in. Inside a machine-language fragment we can produce exactly the same
displacement with <dvar mtp bytesperunit>, so the patterns can be exercised
verbatim.

Memory layout: four adjacent variables are declared in order

    pad0  m1  pad1  m2

  direct   operand -> displacement <dm1>,   effective address m1
  indirect operand -> pointer register = 1 and displacement <dpad0>, so the
           effective address is pad0 + 1 = m1

Aiming the displacement one unit short and setting the index to 1 means the
SIB index register genuinely participates. Pointing it straight at the target
with an index of 0 would pass even if the wrong index register were encoded.

Where one register is both an operand and a pointer, the pointer role wins and
its value is 1; expectations are computed from the same assignment, so the
test stays honest rather than convenient.

Per pattern the program dumps five registers plus m1 and m2 - seven units.
"""

import sys
sys.path.insert(0, ".")
from genmul import enumerate_block, LINO, REG, DIR, IND  # noqa: E402

SENTINEL = [0x11111111, 0x22222222, 0x33333333, 0x44444444, 0x55555555]
TEST_A = 0x12345678
TEST_B = 0xFFFFFFFF          # -1 signed: signedness cannot hide
PTR = 1
M32 = 0xFFFFFFFF
SIGNED = "--unsigned" not in sys.argv
PERPAT = 7

TAG = "mulall" if SIGNED else "mulallu"
SYM = "*%" if SIGNED else "*%'"


def s32(v):
    v &= M32
    return v - 0x100000000 if v & 0x80000000 else v


def product(a, b):
    """Signed or unsigned 64-bit product, matching the instruction under test."""
    return (s32(a) * s32(b)) if SIGNED else ((a & M32) * (b & M32))


def setup(c1, r1, c2, r2):
    """Return (regs, m1, m2) as the program will establish them."""
    regs = list(SENTINEL)
    if c1 == REG: regs[r1] = TEST_A
    if c2 == REG: regs[r2] = TEST_B
    # Pointer roles override: an indirect operand needs a usable index.
    if c1 == IND: regs[r1] = PTR
    if c2 == IND: regs[r2] = PTR
    m1 = TEST_A if c1 in (DIR, IND) else 0
    m2 = TEST_B if c2 in (DIR, IND) else 0
    return regs, m1, m2


def expect(c1, r1, c2, r2):
    regs, m1, m2 = setup(c1, r1, c2, r2)
    a = regs[r1] if c1 == REG else m1
    b = regs[r2] if c2 == REG else m2
    p = product(a, b)
    lo, hi = p & M32, (p >> 32) & M32

    out_regs, out_m1, out_m2 = list(regs), m1, m2
    # op1 receives the low half, op2 the high half.
    if c1 == REG: out_regs[r1] = lo
    else:         out_m1 = lo
    if c2 == REG: out_regs[r2] = hi
    else:         out_m2 = hi
    # Same register as both destinations: low is written first, high second.
    if c1 == REG and c2 == REG and r1 == r2:
        out_regs[r1] = lo          # degenerate case keeps the low half
    return out_regs + [out_m1, out_m2]


def frag(code, c1, c2):
    """Render a pattern as fragment text, substituting the placeholders."""
    d1 = "dm1 mtp bytesperunit" if c1 == DIR else "dpad0 mtp bytesperunit"
    d2 = "dm2 mtp bytesperunit" if c2 == DIR else "dpad1 mtp bytesperunit"
    out = []
    for x in code:
        if isinstance(x, str):
            out.append(f"<{d1 if x.startswith('D1') else d2}>")
        else:
            out.append(f"{x:02X}")
    return " ".join(out)


def main():
    block = enumerate_block(SIGNED)
    src, w = [], None
    src = []
    w = src.append

    w("\n      ( *** mulall - semantic test of all 121 MUL-split patterns *** )\n")
    w("      ( Generated by tools/gentest2.py - do not edit by hand. )\n")
    w('"directors"\n')
    w("\tprogram name = { " + TAG + " };")
    w("\tunit = 32;\n")
    w('"variables"\n')
    w("\tpad0\t= 0;")
    w("\tm1\t= 0;")
    w("\tpad1\t= 0;")
    w("\tm2\t= 0;")
    for i in range(7):
        w(f"\tt{i}\t= 0;")
    w("\n\tresult file name = { " + TAG + ".bin };\n")
    w('"workspace"\n')
    w(f"\tresults = {len(block)} multiplied {PERPAT};\n")
    w('"programme"\n')

    for k, (c1, r1, c2, r2, code, _) in enumerate(block):
        regs, m1, m2 = setup(c1, r1, c2, r2)
        n1 = f"{c1}{LINO[r1]}" if r1 is not None else c1
        n2 = f"{c2}{LINO[r2]}" if r2 is not None else c2
        w(f"\t( ---- {k}: {n1} *% {n2} ---- )")
        w(f"\t[m1] = {m1:08X}h;  [m2] = {m2:08X}h;")
        w("\t[pad0] = 0;  [pad1] = 0;")
        for i, v in enumerate(regs):
            w(f"\t{LINO[i]} = {v:08X}h;")
        w("\t{")
        w(f"\t    {frag(code, c1, c2)}")
        w("\t}")
        for i in range(5):
            w(f"\t[t{i}] = {LINO[i]};")
        w("\tA = [m1]; [t5] = A;  A = [m2]; [t6] = A;")
        w(f"\tA = results; A + {k * PERPAT};")
        for i in range(PERPAT):
            if i:
                w("\tA + 1;")
            w(f"\tC = [t{i}]; [A] = C;")
        w("")

    total = f"{len(block)} multiplied {PERPAT}"
    for cmd in ("WRITE", "SET SIZE"):
        w("\t[File Name]\t= result file name;")
        w("\t[File Position] = 0;")
        w(f"\t[File Command]\t= {cmd};")
        if cmd == "WRITE":
            w("\t[Block Pointer] = results;")
            w(f"\t[Block Size]\t= {total};")
            w("\t[Block Size]\t* BYTES PER UNIT;")
        else:
            w(f"\t[File Size]\t= {total};")
            w("\t[File Size]\t* BYTES PER UNIT;")
        w("\tisocall;")
    w("\n\tend;")

    path = rf"C:\programmieren\linoleum\work\{TAG}.txt"
    open(path, "w").write("\n".join(src) + "\n")
    print(f"wrote {path}  ({len(src)} lines, {len(block)} patterns, {SYM})")

    exp = ["# generated by gentest2.py", "EXPECTED = ["]
    names = []
    for c1, r1, c2, r2, _, _ in block:
        exp.append(f"    {expect(c1, r1, c2, r2)},")
        n1 = f"{c1}{LINO[r1]}" if r1 is not None else c1
        n2 = f"{c2}{LINO[r2]}" if r2 is not None else c2
        names.append(f"{n1} {SYM} {n2}")
    exp.append("]")
    exp.append("NAMES = " + repr(names))
    open(rf"C:\programmieren\linoleum\tools\{TAG}_expect.py", "w").write(
        "\n".join(exp) + "\n")
    print(f"wrote tools/{TAG}_expect.py")


if __name__ == "__main__":
    main()
