"""gentest.py - semantically validate generated MUL-split patterns.

Disassembly proves the patterns are valid x86. It does not prove they compute
the right thing. This does, on real hardware, without touching the toolchain:
each generated byte sequence is emitted as an ordinary machine-language
fragment inside a normal L.in.oleum program.

For each of the 25 register pairs the generated program:
  1. loads all five lino registers with distinct sentinels
  2. overwrites the two operand registers with test values
  3. executes the pattern as a { ... } fragment
  4. writes all five registers out

Python then checks op1 = low 32 bits, op2 = high 32 bits, and - just as
important - that every register which is NOT an operand came back untouched. A
pattern that silently clobbers C would pass a naive value check and then
corrupt the port months later.

Test values are chosen so signedness cannot hide: b = FFFFFFFF is -1 signed,
so a *% b must give high = FFFFFFFF. An unsigned multiply would give
12345677 instead.

Writes: work/mulpat.txt          the lino program
        tools/mulpat_expect.py   what each register should hold
"""

import sys
sys.path.insert(0, ".")
from genmul import gen_reg_reg, LINO  # noqa: E402

SENTINEL = [0x11111111, 0x22222222, 0x33333333, 0x44444444, 0x55555555]
TEST_A = 0x12345678
TEST_B = 0xFFFFFFFF          # -1 signed: makes signed vs unsigned unmistakable
M32 = 0xFFFFFFFF
SIGNED = True


def signed32(v):
    v &= M32
    return v - 0x100000000 if v & 0x80000000 else v


def expected(r1, r2):
    """Register file after pattern (r1, r2) runs, or None where undefined."""
    regs = list(SENTINEL)
    if r1 == r2:
        regs[r1] = TEST_B                      # both loads hit one register
        v = signed32(TEST_B)
        regs[r1] = (v * v) & M32               # low half kept, high dropped
        return regs
    regs[r1] = TEST_A
    regs[r2] = TEST_B
    product = signed32(TEST_A) * signed32(TEST_B)
    regs[r1] = product & M32
    regs[r2] = (product >> 32) & M32
    return regs


def main():
    src = []
    w = src.append
    w("\n      ( *** mulpat - semantic test of generated MUL-split patterns *** )\n")
    w("      ( Generated by tools/gentest.py - do not edit by hand.")
    w("        Each block loads sentinels, sets the two operands, runs one")
    w("        candidate pattern as a machine-language fragment, and dumps")
    w("        all five registers. Nothing in the toolchain is modified. )\n")
    w('"directors"\n')
    w("\tprogram name = { mulpat };")
    w("\tunit = 32;\n")
    w('"variables"\n')
    for i in range(5):
        w(f"\tt{i}\t= 0;")
    w("\n\tresult file name = { mulpat.bin };\n")
    w('"workspace"\n')
    w("\tresults = 25 multiplied 5;\n")
    w('"programme"\n')

    for r1 in range(5):
        for r2 in range(5):
            k = r1 * 5 + r2
            code, _ = gen_reg_reg(r1, r2, SIGNED)
            hexs = " ".join(f"{b:02X}" for b in code)

            w(f"\t( ---- pattern {k}: {LINO[r1]} *% {LINO[r2]} ---- )")
            for i, s in enumerate(SENTINEL):
                w(f"\t{LINO[i]} = {s:08X}h;")
            w(f"\t{LINO[r1]} = {TEST_A:08X}h;")
            w(f"\t{LINO[r2]} = {TEST_B:08X}h;")
            w("\t{")
            w(f"\t    {hexs}")
            w("\t}")
            for i in range(5):
                w(f"\t[t{i}] = {LINO[i]};")
            w(f"\tA = results; A + {k * 5};")
            for i in range(5):
                if i:
                    w("\tA + 1;")
                w(f"\tC = [t{i}]; [A] = C;")
            w("")

    w("\t[File Name]\t= result file name;")
    w("\t[File Position] = 0;")
    w("\t[File Command]\t= WRITE;")
    w("\t[Block Pointer] = results;")
    w("\t[Block Size]\t= 25 multiplied 5;")
    w("\t[Block Size]\t* BYTES PER UNIT;")
    w("\tisocall;")
    w("\t[File Name]\t= result file name;")
    w("\t[File Position] = 0;")
    w("\t[File Command]\t= SET SIZE;")
    w("\t[File Size]\t= 25 multiplied 5;")
    w("\t[File Size]\t* BYTES PER UNIT;")
    w("\tisocall;\n")
    w("\tend;")

    path = r"C:\programmieren\linoleum\work\mulpat.txt"
    open(path, "w").write("\n".join(src) + "\n")
    print(f"wrote {path}  ({len(src)} lines, 25 patterns)")

    exp = ["# generated by gentest.py", "EXPECTED = ["]
    for r1 in range(5):
        for r2 in range(5):
            exp.append(f"    {expected(r1, r2)},  # {LINO[r1]} *% {LINO[r2]}")
    exp.append("]")
    open(r"C:\programmieren\linoleum\tools\mulpat_expect.py", "w").write(
        "\n".join(exp) + "\n")
    print("wrote tools/mulpat_expect.py")


if __name__ == "__main__":
    main()
